package bundle

import (
	"encoding/json"
	"io"
	"strings"
	"time"

	hparender "github.com/mattsu2020/kubectl-hpa-status/pkg/hpa/render"
)

// RenderMarkdown renders all bundle sections to an io.Writer. The first
// write error encountered is returned; rendering otherwise proceeds in order so
// that a partial sink still receives as much of the report as possible.
func RenderMarkdown(w io.Writer, data *Data) error {
	b := &Writer{w: w}
	b.Printf("# HPA Investigation Bundle: %s/%s\n\n", data.Namespace, data.HPAName)
	b.Printf("**Generated:** %s  \n", data.Timestamp.Format(time.RFC3339))
	b.Printf("**Plugin:** kubectl-hpa-status bundle\n\n")
	b.Print("---\n\n")

	writeBundleTOC(b)
	b.Print("---\n\n")

	writeBundleStatusSummary(b, data)
	writeBundleHPAYAML(b, data)
	writeBundleScaleTarget(b, data)
	writeBundlePodStatusTable(b, data)
	writeBundleContainerStatusTable(b, data)
	writeBundleResourceRequests(b, data)
	writeBundleEventsSection(b, data)
	writeBundleMetricsAPI(b, data)
	writeBundleMetricsDiagnostics(b, data)
	writeBundleCapacityContextSection(b, data)
	writeBundleScalePathSection(b, data)
	writeBundleBlockerSection(b, data)
	writeBundleKEDASection(b, data)
	writeBundleQuotasSection(b, data)
	writeBundleLimitRangesSection(b, data)
	writeBundlePDBsSection(b, data)
	writeBundleNodeCapacitySection(b, data)
	writeBundleRecommendations(b, data)
	writeBundleFullAnalysis(b, data)
	writeBundleWarnings(b, data)

	b.Print("---\n_Generated by kubectl-hpa-status bundle_\n")
	return b.err
}

func writeBundleTOC(b *Writer) {
	b.Print("## Table of Contents\n\n")
	sections := []string{
		"HPA Status Summary",
		"HPA Resource (YAML)",
		"Scale Target Resource",
		"Pod Status",
		"Container Status",
		"Resource Requests/Limits",
		"Events",
		"Metrics API Status",
		"Metrics Diagnostics",
		"Capacity Context",
		"Scale Path",
		"Blocker Analysis",
		"KEDA Status",
		"ResourceQuotas",
		"LimitRanges",
		"PodDisruptionBudgets",
		"Node Capacity",
		"Recommendations",
		"Full Analysis Report",
	}
	for i, s := range sections {
		anchor := strings.ToLower(strings.ReplaceAll(s, " ", "-"))
		anchor = strings.ReplaceAll(anchor, "(", "")
		anchor = strings.ReplaceAll(anchor, ")", "")
		anchor = strings.ReplaceAll(anchor, "/", "")
		b.Printf("%d. [%s](#%s)\n", i+1, s, anchor)
	}
	b.Println()
}

func writeBundleStatusSummary(b *Writer, data *Data) {
	b.Print("## HPA Status Summary\n\n")
	if err := hparender.WriteMarkdownReport(b.w, data.StatusReport); err != nil {
		b.Printf("_Error rendering status summary: %v_\n", err)
	}
	b.Print("\n---\n\n")
}

func writeBundleHPAYAML(b *Writer, data *Data) {
	b.Print("## HPA Resource (YAML)\n\n")
	b.Print("```yaml\n")
	b.Write(data.HPA)
	b.Print("```\n\n---\n\n")
}

func writeBundleScaleTarget(b *Writer, data *Data) {
	b.Print("## Scale Target Resource\n\n")
	b.Print("```yaml\n")
	b.Write(data.ScaleTarget)
	b.Print("```\n\n---\n\n")
}

func writeBundlePodStatusTable(b *Writer, data *Data) {
	b.Print("## Pod Status\n\n")
	if len(data.PodInfos) == 0 {
		b.Print("_No pod information available._\n\n---\n\n")
		return
	}

	b.Print("| Name | Phase | Ready | Unschedulable | Reasons | Node |\n")
	b.Print("|------|-------|-------|---------------|---------|------|\n")
	for _, pod := range data.PodInfos {
		ready := "✓"
		if !pod.Ready {
			ready = "✗"
		}
		unschedulable := "-"
		if pod.Unschedulable {
			unschedulable = "Yes"
		}
		reasons := "-"
		if len(pod.Reasons) > 0 {
			reasons = mdEscape(strings.Join(pod.Reasons, ", "))
		}
		node := pod.NodeName
		if node == "" {
			node = "-"
		}
		b.Printf("| %s | %s | %s | %s | %s | %s |\n",
			mdEscape(pod.Name), mdEscape(pod.Phase), ready, unschedulable, reasons, mdEscape(node))
	}
	b.Print("\n---\n\n")
}

func writeBundleContainerStatusTable(b *Writer, data *Data) {
	b.Print("## Container Status\n\n")
	if len(data.ContainerStatuses) == 0 {
		b.Print("_No container status data available._\n\n---\n\n")
		return
	}

	b.Print("| Pod | Container | Waiting | Waiting Reason | Restarts |\n")
	b.Print("|-----|-----------|---------|----------------|----------|\n")
	for _, cs := range data.ContainerStatuses {
		waiting := "No"
		if cs.Waiting {
			waiting = "Yes"
		}
		waitReason := "-"
		if cs.WaitingReason != "" {
			waitReason = mdEscape(cs.WaitingReason)
		}
		b.Printf("| %s | %s | %s | %s | %d |\n",
			mdEscape(cs.Pod), mdEscape(cs.Container), waiting, waitReason, cs.RestartCount)
	}
	b.Print("\n---\n\n")
}

func writeBundleResourceRequests(b *Writer, data *Data) {
	b.Print("## Resource Requests/Limits\n\n")
	rc := data.StatusReport.Analysis.ResourceCheck
	if rc == nil || len(rc.Warnings) == 0 {
		b.Print("_No resource consistency issues detected._\n\n---\n\n")
		return
	}

	b.Print("| Container | Resource | Category | Severity | Details |\n")
	b.Print("|-----------|----------|----------|----------|--------|\n")
	for _, warn := range rc.Warnings {
		b.Printf("| %s | %s | %s | %s | %s |\n",
			mdEscape(warn.Container), mdEscape(warn.Resource),
			mdEscape(warn.Category), mdEscape(warn.Severity), mdEscape(warn.Details))
	}
	b.Print("\n---\n\n")
}

func writeBundleCapacityContextSection(b *Writer, data *Data) {
	b.Print("## Capacity Context\n\n")
	cc := data.StatusReport.Analysis.CapacityContext
	if cc == nil {
		b.Print("_No capacity context available._\n\n---\n\n")
		return
	}

	if len(cc.PendingPods) > 0 {
		b.Print("### Pending Pods\n\n")
		b.Print("| Name | Unschedulable | Reasons |\n")
		b.Print("|------|--------------|---------|\n")
		for _, pod := range cc.PendingPods {
			unsched := "No"
			if pod.Unschedulable {
				unsched = "Yes"
			}
			reasons := "-"
			if len(pod.Reasons) > 0 {
				reasons = mdEscape(strings.Join(pod.Reasons, ", "))
			}
			b.Printf("| %s | %s | %s |\n", mdEscape(pod.Name), unsched, reasons)
		}
		b.Println()
	}

	if len(cc.QuotaConstraints) > 0 {
		b.Print("### Quota Constraints\n\n")
		b.Print("| Name | Resource | Used | Hard | Message |\n")
		b.Print("|------|----------|------|------|---------|\n")
		for _, q := range cc.QuotaConstraints {
			b.Printf("| %s | %s | %s | %s | %s |\n",
				mdEscape(q.Name), mdEscape(q.Resource),
				mdEscape(q.Used), mdEscape(q.Hard), mdEscape(q.Message))
		}
		b.Println()
	}

	if len(cc.PDBInterference) > 0 {
		b.Print("### PDB Interference\n\n")
		b.Print("| Name | Min Available | Max Unavailable | Disruption |\n")
		b.Print("|------|--------------|----------------|------------|\n")
		for _, pdb := range cc.PDBInterference {
			b.Printf("| %s | %s | %s | %s |\n",
				mdEscape(pdb.Name), mdEscape(pdb.MinAvailable),
				mdEscape(pdb.MaxUnavailable), mdEscape(pdb.Disruption))
		}
		b.Println()
	}

	if len(cc.NodeHints) > 0 {
		b.Print("### Node Hints\n\n")
		for _, hint := range cc.NodeHints {
			b.Printf("- %s\n", mdEscape(hint))
		}
		b.Println()
	}

	b.Print("\n---\n\n")
}

func writeBundleScalePathSection(b *Writer, data *Data) {
	b.Print("## Scale Path\n\n")
	sp := data.StatusReport.Analysis.ScalePath
	if sp == nil {
		b.Print("_No scale path analysis available._\n\n---\n\n")
		return
	}

	if len(sp.Steps) > 0 {
		b.Print("| Step | Name | Summary |\n")
		b.Print("|------|------|--------|\n")
		for i, step := range sp.Steps {
			b.Printf("| %d | %s | %s |\n",
				i+1, mdEscape(step.Name), mdEscape(step.Summary))
		}
		b.Println()
	}

	if sp.BlockingPoint != "" {
		b.Printf("**Blocking Point:** %s\n\n", mdEscape(sp.BlockingPoint))
	}

	if len(sp.Evidence) > 0 {
		b.Print("**Evidence:**\n")
		for _, e := range sp.Evidence {
			b.Printf("- %s\n", mdEscape(e))
		}
		b.Println()
	}

	if len(sp.NextActions) > 0 {
		b.Print("**Next Actions:**\n")
		for _, a := range sp.NextActions {
			b.Printf("- %s\n", mdEscape(a))
		}
		b.Println()
	}

	b.Print("\n---\n\n")
}

func writeBundleBlockerSection(b *Writer, data *Data) {
	b.Print("## Blocker Analysis\n\n")
	br := data.StatusReport.Analysis.BlockerReport
	if br == nil {
		b.Print("_No blocker analysis available._\n\n---\n\n")
		return
	}

	b.Printf("**Summary:** %s\n\n", mdEscape(br.Summary))
	b.Printf("**HPA Wants Scale:** %v | **Desired:** %d | **Ready:** %d\n\n",
		br.HPAWantsScale, br.DesiredReplicas, br.ReadyReplicas)

	if len(br.Blockers) > 0 {
		b.Print("| Severity | Category | Message | Detail |\n")
		b.Print("|----------|----------|---------|--------|\n")
		for _, block := range br.Blockers {
			b.Printf("| %s | %s | %s | %s |\n",
				mdEscape(string(block.Severity)), mdEscape(block.Category),
				mdEscape(block.Message), mdEscape(block.Detail))
		}
		b.Println()
	}

	if br.Interpretation != "" {
		b.Printf("**Interpretation:** %s\n\n", mdEscape(br.Interpretation))
	}

	if len(br.NextCommands) > 0 {
		b.Print("**Investigation Commands:**\n")
		for _, cmd := range br.NextCommands {
			b.Printf("```bash\n%s\n```\n", cmd)
		}
		b.Println()
	}

	b.Print("\n---\n\n")
}

func writeBundleKEDASection(b *Writer, data *Data) {
	ki := data.StatusReport.Analysis.KEDAInfo
	if ki == nil {
		return // Omit entire section when KEDA is not detected.
	}

	b.Print("## KEDA Status\n\n")
	b.Printf("**ScaledObject:** %s\n\n", mdEscape(ki.ScaledObjectName))

	if ki.PollingInterval != nil {
		b.Printf("**Polling Interval:** %ds\n", *ki.PollingInterval)
	}
	if ki.CooldownPeriod != nil {
		b.Printf("**Cooldown Period:** %ds\n", *ki.CooldownPeriod)
	}
	if ki.MinReplicaCount != nil {
		b.Printf("**Min Replica Count:** %d\n", *ki.MinReplicaCount)
	}
	if ki.MaxReplicaCount != nil {
		b.Printf("**Max Replica Count:** %d\n", *ki.MaxReplicaCount)
	}

	if len(ki.Triggers) > 0 {
		b.Print("\n### Triggers\n\n")
		b.Print("| Type | Name | Status | Threshold | Current | Auth Ref |\n")
		b.Print("|------|------|--------|-----------|---------|----------|\n")
		for _, t := range ki.Triggers {
			authRef := "-"
			if t.AuthRef != "" {
				authRef = mdEscape(t.AuthRef)
			}
			b.Printf("| %s | %s | %s | %s | %s | %s |\n",
				mdEscape(t.Type), mdEscape(t.Name), mdEscape(t.Status),
				mdEscape(t.Threshold), mdEscape(t.CurrentValue), authRef)
		}
		b.Println()
	}

	if ki.Fallback != nil {
		b.Printf("**Fallback:** failureThreshold=%d, replicas=%d\n\n",
			ki.Fallback.FailureThreshold, ki.Fallback.Replicas)
	}

	if len(ki.Lines) > 0 {
		b.Print("**Notes:**\n")
		for _, line := range ki.Lines {
			b.Printf("- %s\n", mdEscape(line))
		}
		b.Println()
	}

	b.Print("\n---\n\n")
}

func writeBundleQuotasSection(b *Writer, data *Data) {
	b.Print("## ResourceQuotas\n\n")
	if len(data.ResourceQuotas) == 0 {
		b.Print("_No ResourceQuotas found in namespace._\n\n---\n\n")
		return
	}

	b.Print("| Name | Resource | Used | Hard | Ratio |\n")
	b.Print("|------|----------|------|------|-------|\n")
	for _, q := range data.ResourceQuotas {
		b.Printf("| %s | %s | %s | %s | %.0f%% |\n",
			mdEscape(q.Name), mdEscape(q.Resource),
			mdEscape(q.Used), mdEscape(q.Hard), q.Ratio*100)
	}
	b.Print("\n---\n\n")
}

func writeBundleLimitRangesSection(b *Writer, data *Data) {
	b.Print("## LimitRanges\n\n")
	if len(data.LimitRanges) == 0 {
		b.Print("_No LimitRanges found in namespace._\n\n---\n\n")
		return
	}

	b.Print("| Name | Type | Resource | Min | Max |\n")
	b.Print("|------|------|----------|-----|-----|\n")
	for _, lr := range data.LimitRanges {
		minVal := "-"
		if lr.Min != "" {
			minVal = mdEscape(lr.Min)
		}
		maxVal := "-"
		if lr.Max != "" {
			maxVal = mdEscape(lr.Max)
		}
		b.Printf("| %s | %s | %s | %s | %s |\n",
			mdEscape(lr.Name), mdEscape(lr.Type),
			mdEscape(lr.Resource), minVal, maxVal)
	}
	b.Print("\n---\n\n")
}

func writeBundlePDBsSection(b *Writer, data *Data) {
	b.Print("## PodDisruptionBudgets\n\n")
	if len(data.PDBs) == 0 {
		b.Print("_No PodDisruptionBudgets found in namespace._\n\n---\n\n")
		return
	}

	b.Print("| Name | Min Available | Max Unavailable |\n")
	b.Print("|------|--------------|----------------|\n")
	for _, pdb := range data.PDBs {
		minAvail := "-"
		if pdb.MinAvailable != "" {
			minAvail = mdEscape(pdb.MinAvailable)
		}
		maxUnavail := "-"
		if pdb.MaxUnavailable != "" {
			maxUnavail = mdEscape(pdb.MaxUnavailable)
		}
		b.Printf("| %s | %s | %s |\n",
			mdEscape(pdb.Name), minAvail, maxUnavail)
	}
	b.Print("\n---\n\n")
}

func writeBundleNodeCapacitySection(b *Writer, data *Data) {
	b.Print("## Node Capacity\n\n")
	if data.NodeCapacity == nil {
		b.Print("_Node capacity information unavailable._\n\n---\n\n")
		return
	}

	nc := data.NodeCapacity
	b.Print("| Metric | Value |\n")
	b.Print("|--------|-------|\n")
	b.Printf("| Total Nodes | %d |\n", nc.TotalNodes)
	b.Printf("| Allocatable CPU | %s |\n", nc.AllocCPU.String())
	b.Printf("| Allocatable Memory | %s |\n", nc.AllocMemory.String())
	b.Printf("| Tainted Nodes | %d |\n", nc.TaintedNodes)
	b.Print("\n---\n\n")
}

func writeBundleRecommendations(b *Writer, data *Data) {
	b.Print("## Recommendations\n\n")
	a := data.StatusReport.Analysis

	if len(a.Actions) > 0 {
		b.Print("### Actions\n\n")
		for _, action := range a.Actions {
			b.Printf("- %s\n", mdEscape(action))
		}
		b.Println()
	}

	if len(a.Suggestions) > 0 {
		b.Print("### Suggestions\n\n")
		for _, s := range a.Suggestions {
			b.Printf("- %s\n", mdEscape(s.Description))
		}
		b.Println()
	}

	if len(a.Interpretation) > 0 {
		b.Print("### Interpretation\n\n")
		for _, interp := range a.Interpretation {
			b.Printf("- %s\n", mdEscape(interp))
		}
		b.Println()
	}

	if len(a.Actions) == 0 && len(a.Suggestions) == 0 && len(a.Interpretation) == 0 {
		b.Print("_No recommendations available._\n")
	}

	b.Print("\n---\n\n")
}

func writeBundleFullAnalysis(b *Writer, data *Data) {
	b.Print("## Full Analysis Report\n\n")
	b.Print("<details><summary>Raw JSON Analysis</summary>\n\n")
	b.Print("```json\n")

	analysisJSON, err := json.MarshalIndent(data.StatusReport.Analysis, "", "  ")
	if err != nil {
		b.Printf("Error serializing analysis: %v\n", err)
	} else {
		b.Write(analysisJSON)
	}

	b.Print("\n```\n\n</details>\n\n")
}

// writeBundleWarnings renders the collection warnings section. Each warning
// records a non-fatal fetch failure (RBAC denial, API timeout, etc.) so the
// bundle consumer can see why a section is empty rather than guessing. When
// there are no warnings the section is omitted entirely.
func writeBundleWarnings(b *Writer, data *Data) {
	if len(data.Warnings) == 0 {
		return
	}
	b.Print("## Collection Warnings\n\n")
	b.Print("_Some data sources could not be collected. The sections above may be incomplete or empty as a result._\n\n")
	for _, w := range data.Warnings {
		b.Printf("- %s\n", w)
	}
	b.Print("\n---\n\n")
}

// mdEscape escapes the pipe character for safe use inside markdown tables.
func mdEscape(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}
