package bundle

import (
	"encoding/json"
	"io"
	"strings"
	"time"

	hparender "github.com/mattsu2020/kubectl-hpa-status/pkg/hpa/render"
)

// RenderMarkdown renders all bundle sections to an io.Writer. The first
// write error encountered is returned; rendering otherwise proceeds in order so
// that a partial sink still receives as much of the report as possible.
func RenderMarkdown(w io.Writer, data *Data) error {
	b := &Writer{w: w}
	b.Printf("# HPA Investigation Bundle: %s/%s\n\n", data.Namespace, data.HPAName)
	b.Printf("**Generated:** %s  \n", data.Timestamp.Format(time.RFC3339))
	b.Printf("**Plugin:** kubectl-hpa-status bundle\n\n")
	b.Print("---\n\n")

	writeBundleTOC(b)
	b.Print("---\n\n")

	writeBundleStatusSummary(b, data)
	writeBundleHPAYAML(b, data)
	writeBundleScaleTarget(b, data)
	writeBundlePodStatusTable(b, data)
	writeBundleContainerStatusTable(b, data)
	writeBundleResourceRequests(b, data)
	writeBundleEventsSection(b, data)
	writeBundleMetricsAPI(b, data)
	writeBundleMetricsDiagnostics(b, data)
	writeBundleCapacityContextSection(b, data)
	writeBundleScalePathSection(b, data)
	writeBundleBlockerSection(b, data)
	writeBundleKEDASection(b, data)
	writeBundleQuotasSection(b, data)
	writeBundleLimitRangesSection(b, data)
	writeBundlePDBsSection(b, data)
	writeBundleNodeCapacitySection(b, data)
	writeBundleRecommendations(b, data)
	writeBundleFullAnalysis(b, data)
	writeBundleWarnings(b, data)

	b.Print("---\n_Generated by kubectl-hpa-status bundle_\n")
	return b.err
}

func writeBundleTOC(b *Writer) {
	b.Print("## Table of Contents\n\n")
	sections := []string{
		"HPA Status Summary",
		"HPA Resource (YAML)",
		"Scale Target Resource",
		"Pod Status",
		"Container Status",
		"Resource Requests/Limits",
		"Events",
		"Metrics API Status",
		"Metrics Diagnostics",
		"Capacity Context",
		"Scale Path",
		"Blocker Analysis",
		"KEDA Status",
		"ResourceQuotas",
		"LimitRanges",
		"PodDisruptionBudgets",
		"Node Capacity",
		"Recommendations",
		"Full Analysis Report",
	}
	for i, s := range sections {
		anchor := strings.ToLower(strings.ReplaceAll(s, " ", "-"))
		anchor = strings.ReplaceAll(anchor, "(", "")
		anchor = strings.ReplaceAll(anchor, ")", "")
		anchor = strings.ReplaceAll(anchor, "/", "")
		b.Printf("%d. [%s](#%s)\n", i+1, s, anchor)
	}
	b.Println()
}

func writeBundleStatusSummary(b *Writer, data *Data) {
	b.Print("## HPA Status Summary\n\n")
	if err := hparender.WriteMarkdownReport(b.w, data.StatusReport); err != nil {
		b.Printf("_Error rendering status summary: %v_\n", err)
	}
	b.Print("\n---\n\n")
}

func writeBundleHPAYAML(b *Writer, data *Data) {
	b.Print("## HPA Resource (YAML)\n\n")
	b.Print("```yaml\n")
	b.Write(data.HPA)
	b.Print("```\n\n---\n\n")
}

func writeBundleScaleTarget(b *Writer, data *Data) {
	b.Print("## Scale Target Resource\n\n")
	b.Print("```yaml\n")
	b.Write(data.ScaleTarget)
	b.Print("```\n\n---\n\n")
}

func writeBundleRecommendations(b *Writer, data *Data) {
	b.Print("## Recommendations\n\n")
	a := data.StatusReport.Analysis

	if len(a.Actions()) > 0 {
		b.Print("### Actions\n\n")
		for _, action := range a.Actions() {
			b.Printf("- %s\n", mdEscape(action))
		}
		b.Println()
	}

	if len(a.Suggestions()) > 0 {
		b.Print("### Suggestions\n\n")
		for _, s := range a.Suggestions() {
			b.Printf("- %s\n", mdEscape(s.Description))
		}
		b.Println()
	}

	if len(a.Interpretation()) > 0 {
		b.Print("### Interpretation\n\n")
		for _, interp := range a.Interpretation() {
			b.Printf("- %s\n", mdEscape(interp))
		}
		b.Println()
	}

	if len(a.Actions()) == 0 && len(a.Suggestions()) == 0 && len(a.Interpretation()) == 0 {
		b.Print("_No recommendations available._\n")
	}

	b.Print("\n---\n\n")
}

func writeBundleFullAnalysis(b *Writer, data *Data) {
	b.Print("## Full Analysis Report\n\n")
	b.Print("<details><summary>Raw JSON Analysis</summary>\n\n")
	b.Print("```json\n")

	analysisJSON, err := json.MarshalIndent(data.StatusReport.Analysis, "", "  ")
	if err != nil {
		b.Printf("Error serializing analysis: %v\n", err)
	} else {
		b.Write(analysisJSON)
	}

	b.Print("\n```\n\n</details>\n\n")
}

// writeBundleWarnings renders the collection warnings section. Each warning
// records a non-fatal fetch failure (RBAC denial, API timeout, etc.) so the
// bundle consumer can see why a section is empty rather than guessing. When
// there are no warnings the section is omitted entirely.
func writeBundleWarnings(b *Writer, data *Data) {
	if len(data.Warnings) == 0 {
		return
	}
	b.Print("## Collection Warnings\n\n")
	b.Print("_Some data sources could not be collected. The sections above may be incomplete or empty as a result._\n\n")
	for _, w := range data.Warnings {
		b.Printf("- %s\n", w)
	}
	b.Print("\n---\n\n")
}

// mdEscape escapes the pipe character for safe use inside markdown tables.
func mdEscape(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}
