package bundle

import (
	"bytes"
	"strings"
	"testing"
	"time"

	hpaanalysis "github.com/mattsu2020/kubectl-hpa-status/pkg/hpa"
)

// TestWriteBundleMarkdown_RenderAllSections drives every writeBundle* renderer
// through the single writeBundleMarkdown entrypoint with a fully-populated
// bundleData fixture, asserting that each section header appears in the output.
// This is the highest-ROI test for this file: one call exercises ~20 renderers.
func TestWriteBundleMarkdown_RenderAllSections(t *testing.T) {
	data := &Data{
		Namespace:    "production",
		HPAName:      "web",
		Timestamp:    time.Date(2025, 1, 2, 3, 4, 5, 0, time.UTC),
		HPA:          []byte("# raw HPA yaml"),
		ScaleTarget:  []byte("# scale target yaml"),
		ReplicaSets:  []byte("# replicasets yaml"),
		Pods:         []byte("# pods yaml"),
		Events:       []byte("# events yaml"),
		MetricsAPI:   []byte("# metrics api yaml"),
		Warnings:     []string{"could not read node X"},
		StatusReport: hpaanalysis.StatusReport{},
	}

	var buf bytes.Buffer
	if err := RenderMarkdown(&buf, data); err != nil {
		t.Fatalf("writeBundleMarkdown: %v", err)
	}
	out := buf.String()

	// Document header.
	if !strings.Contains(out, "# HPA Investigation Bundle: production/web") {
		t.Fatalf("expected bundle header, got first 200 bytes:\n%s", firstNLocal(out, 200))
	}
	if !strings.Contains(out, "**Generated:** 2025-01-02T03:04:05Z") {
		t.Fatalf("expected RFC3339 timestamp, got:\n%s", firstNLocal(out, 200))
	}

	// All major section renderers must contribute output. Check a
	// representative header/keyword from each (matched as prefixes of the
	// actual section titles in bundle_markdown.go).
	requiredSubstrings := []string{
		"## HPA Status Summary",   // writeBundleStatusSummary
		"## HPA Resource",         // writeBundleHPAYAML
		"## Scale Target",         // writeBundleScaleTarget
		"## Pod Status",           // writeBundlePodStatusTable
		"## Container Status",     // writeBundleContainerStatusTable
		"## Resource Requests",    // writeBundleResourceRequests
		"## Events",               // writeBundleEventsSection
		"## Metrics API",          // writeBundleMetricsAPI
		"## Capacity Context",     // writeBundleCapacityContextSection
		"## Scale Path",           // writeBundleScalePathSection
		"## Blocker Analysis",     // writeBundleBlockerSection
		"## ResourceQuotas",       // writeBundleQuotasSection
		"## LimitRanges",          // writeBundleLimitRangesSection
		"## PodDisruptionBudgets", // writeBundlePDBsSection
		"## Node Capacity",        // writeBundleNodeCapacitySection
		"## Recommendations",      // writeBundleRecommendations
		"## Full Analysis Report", // writeBundleFullAnalysis
		"## Collection Warnings",  // writeBundleWarnings
		"could not read node X",   // the warning payload
	}
	for _, want := range requiredSubstrings {
		if !strings.Contains(out, want) {
			t.Errorf("expected %q in bundle output", want)
		}
	}

	// Footer sentinel from the final Print call.
	if !strings.Contains(out, "Generated by kubectl-hpa-status bundle") {
		t.Errorf("expected footer sentinel")
	}
}

// TestWriteBundleMarkdown_MinimalDataNoPanic ensures the renderers tolerate
// an empty bundleData (all nil/zero) without panicking — every section must
// be no-op-safe when its input is absent, since bundle collection is
// best-effort and individual sections frequently have no data.
func TestWriteBundleMarkdown_MinimalDataNoPanic(t *testing.T) {
	data := &Data{
		Namespace: "default",
		HPAName:   "missing-sections",
		Timestamp: time.Time{},
	}
	var buf bytes.Buffer
	if err := RenderMarkdown(&buf, data); err != nil {
		t.Fatalf("writeBundleMarkdown on minimal data: %v", err)
	}
	if !strings.Contains(buf.String(), "# HPA Investigation Bundle: default/missing-sections") {
		t.Fatal("expected header even for minimal data")
	}
}

// TestWriteBundleMarkdown_PropagatesWriteError verifies that a failing writer
// surfaces the first error rather than being swallowed by the renderer.
func TestWriteBundleMarkdown_PropagatesWriteError(t *testing.T) {
	data := &Data{
		Namespace: "ns",
		HPAName:   "hpa",
		Timestamp: time.Now(),
	}
	err := RenderMarkdown(&failingWriter{}, data)
	if err == nil {
		t.Fatal("expected error from failing writer, got nil")
	}
}

// firstNLocal is a local copy to avoid coupling to the e2e-only firstN helper.
func firstNLocal(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n]
}

// failingWriter is an io.Writer that always returns an error.
type failingWriter struct{}

func (failingWriter) Write(_ []byte) (int, error) {
	return 0, errFailingWriterStub
}

var errFailingWriterStub = bytes.ErrTooLarge // reuse a stable sentinel error
