version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      kubernetes:
        patterns:
          - k8s.io/*
      golang-x:
        patterns:
          - golang.org/x/*
      charmbracelet:
        patterns:
          - github.com/charmbracelet/*
          - github.com/muesli/*
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
