package hpa

import (
	"fmt"
	"io"
	"sort"
	"strings"
	"time"
)

// WriteRichIncidentMarkdown generates a comprehensive incident report in
// Markdown format from one or more StatusReports. The report includes
// incident summary, executive summary table, timeline, root cause analysis,
// affected workloads, remediation steps, capacity context, recommendations,
// and escalation notes.
func WriteRichIncidentMarkdown(out io.Writer, reports []StatusReport) error {
	var buf strings.Builder
	current := now().UTC()

	// Derive a short title from HPA names.
	names := incidentReportNames(reports)

	// --- 1. Incident Summary ---
	buf.WriteString("# HPA Incident Report: ")
	buf.WriteString(names)
	buf.WriteString("\n\n")

	severity := overallSeverity(reports)
	buf.WriteString("## Incident Summary\n\n")
	buf.WriteString(fmt.Sprintf("- **Generated:** %s\n", current.Format(time.RFC3339)))
	buf.WriteString(fmt.Sprintf("- **Severity:** SEVERITY: %s\n", severity))
	buf.WriteString(fmt.Sprintf("- **Affected HPAs:** %d\n", len(reports)))

	if len(reports) == 0 {
		buf.WriteString("\nNo HPAs to report.\n")
		buf.WriteString("\n---\nGenerated by kubectl-hpa-status\n")
		_, err := io.WriteString(out, buf.String())
		return err
	}
	buf.WriteString("\n")

	// --- 2. Executive Summary Table ---
	writeIncidentExecutiveSummary(&buf, reports)

	// --- 3. Timeline of Events ---
	writeIncidentTimeline(&buf, reports)

	// --- 4. Root Cause Analysis ---
	writeIncidentRootCause(&buf, reports)

	// --- 5. Affected Workloads ---
	writeIncidentAffectedWorkloads(&buf, reports)

	// --- 6. Remediation Steps ---
	writeIncidentRemediationSteps(&buf, reports)

	// --- 7. Capacity Context ---
	writeIncidentCapacityContext(&buf, reports)

	// --- 8. Recommendations ---
	writeIncidentRecommendations(&buf, reports)

	// --- 9. Escalation Notes ---
	writeIncidentEscalationNotes(&buf, reports)

	buf.WriteString("---\nGenerated by kubectl-hpa-status\n")

	_, err := io.WriteString(out, buf.String())
	return err
}

// writeIncidentExecutiveSummary renders the per-HPA summary table.
func writeIncidentExecutiveSummary(buf *strings.Builder, reports []StatusReport) {
	buf.WriteString("## Executive Summary\n\n")
	buf.WriteString("| Namespace | Name | Health | Score | Current | Desired | Min | Max |\n")
	buf.WriteString("|-----------|------|--------|-------|---------|---------|-----|-----|\n")
	for _, r := range reports {
		a := r.Analysis
		buf.WriteString(fmt.Sprintf("| %s | %s | %s | %d | %d | %d | %d | %d |\n",
			escapeMarkdown(a.Namespace),
			escapeMarkdown(a.Name),
			severityPrefix(a.Health),
			a.HealthScore,
			a.Current,
			a.Desired,
			a.Min,
			a.Max,
		))
	}
	buf.WriteString("\n")
}

// writeIncidentTimeline renders the events timeline when any report has events.
func writeIncidentTimeline(buf *strings.Builder, reports []StatusReport) {
	hasEvents := false
	for _, r := range reports {
		if len(r.Events) > 0 {
			hasEvents = true
			break
		}
	}
	if !hasEvents {
		return
	}
	buf.WriteString("## Timeline of Events\n\n")
	for _, r := range reports {
		if len(r.Events) == 0 {
			continue
		}
		a := r.Analysis
		buf.WriteString(fmt.Sprintf("### %s/%s\n\n", a.Namespace, a.Name))
		buf.WriteString("| Timestamp | Reason | Message |\n")
		buf.WriteString("|-----------|--------|--------|\n")
		sorted := make([]Event, len(r.Events))
		copy(sorted, r.Events)
		sort.Slice(sorted, func(i, j int) bool {
			return sorted[i].Timestamp.Before(sorted[j].Timestamp)
		})
		for _, e := range sorted {
			ts := ""
			if !e.Timestamp.IsZero() {
				ts = e.Timestamp.Format(time.RFC3339)
			}
			buf.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				ts,
				escapeMarkdown(e.Reason),
				escapeMarkdown(e.Message),
			))
		}
		buf.WriteString("\n")
	}
}

// writeIncidentRootCause renders the root cause analysis section per HPA.
func writeIncidentRootCause(buf *strings.Builder, reports []StatusReport) {
	buf.WriteString("## Root Cause Analysis\n\n")
	for _, r := range reports {
		a := r.Analysis
		buf.WriteString(fmt.Sprintf("### %s/%s\n\n", a.Namespace, a.Name))

		writeRootCauseConditions(buf, a)
		writeRootCauseMetricsPipeline(buf, a)
		writeRootCauseChurn(buf, a)
		writeRootCauseAnomalies(buf, a)

		// If no specific analysis was available, emit the summary.
		if len(a.Conditions) == 0 && a.MetricsDiagnostics == nil && a.ChurnAnalysis == nil && a.HealthTrend == nil {
			if a.Summary != "" {
				buf.WriteString(fmt.Sprintf("%s\n\n", a.Summary))
			} else {
				buf.WriteString("No detailed root cause data available.\n\n")
			}
		}
	}
}

// writeRootCauseConditions renders the Conditions subsection of root cause.
func writeRootCauseConditions(buf *strings.Builder, a Analysis) {
	if len(a.Conditions) == 0 {
		return
	}
	buf.WriteString("**Conditions:**\n\n")
	for _, c := range a.Conditions {
		implication := conditionImplication(c)
		buf.WriteString(fmt.Sprintf("- **%s** (%s): %s — %s\n",
			c.Type, c.Status, escapeMarkdown(c.Reason), implication))
	}
	buf.WriteString("\n")
}

// writeRootCauseMetricsPipeline renders the metrics pipeline diagnostics subsection.
func writeRootCauseMetricsPipeline(buf *strings.Builder, a Analysis) {
	if a.MetricsDiagnostics == nil {
		return
	}
	buf.WriteString(fmt.Sprintf("**Metrics Pipeline:** %s\n\n", a.MetricsDiagnostics.OverallStatus))
	for _, check := range a.MetricsDiagnostics.PerMetricChecks {
		buf.WriteString(fmt.Sprintf("- %s/%s: %s — %s\n",
			check.MetricType, check.MetricName, check.Status, escapeMarkdown(check.Details)))
	}
	if len(a.MetricsDiagnostics.RemediationSteps) > 0 {
		buf.WriteString("\n**Remediation Steps:**\n\n")
		for _, step := range a.MetricsDiagnostics.RemediationSteps {
			buf.WriteString(fmt.Sprintf("- %s\n", step))
		}
	}
	buf.WriteString("\n")
}

// writeRootCauseChurn renders the churn analysis subsection.
func writeRootCauseChurn(buf *strings.Builder, a Analysis) {
	if a.ChurnAnalysis == nil {
		return
	}
	ca := a.ChurnAnalysis
	buf.WriteString(fmt.Sprintf("**Churn Detected:** level=%s score=%d flips=%d (scale-ups=%d scale-downs=%d)\n\n",
		ca.Level, ca.Score, ca.DirectionFlips, ca.ScaleUpCount, ca.ScaleDownCount))
	for _, rec := range ca.Recommendations {
		buf.WriteString(fmt.Sprintf("- **%s:** change %s -> %s — %s\n",
			rec.Type, rec.CurrentValue, rec.RecommendedValue, rec.Rationale))
	}
	buf.WriteString("\n")
}

// writeRootCauseAnomalies renders the health-trend anomaly subsection.
func writeRootCauseAnomalies(buf *strings.Builder, a Analysis) {
	if a.HealthTrend == nil || len(a.HealthTrend.Anomalies) == 0 {
		return
	}
	buf.WriteString("**Anomaly Detection:**\n\n")
	for _, anomaly := range a.HealthTrend.Anomalies {
		buf.WriteString(fmt.Sprintf("- **%s** (severity: %s): score changed %d -> %d",
			anomaly.Type, anomaly.Severity, anomaly.ScoreBefore, anomaly.ScoreAfter))
		if anomaly.CauseEstimate != "" {
			buf.WriteString(fmt.Sprintf("\n  - Cause: %s", anomaly.CauseEstimate))
		}
		if anomaly.Remediation != "" {
			buf.WriteString(fmt.Sprintf("\n  - Remediation: %s", anomaly.Remediation))
		}
		buf.WriteString("\n")
	}
	if a.HealthTrend.FlappingDetected {
		buf.WriteString(fmt.Sprintf("- **Flapping detected** (variance: %.1f)\n", a.HealthTrend.Variance))
	}
	buf.WriteString("\n")
}
