package hpa

import (
	"bytes"
	"strings"
	"testing"
	"time"
)

func TestWriteRichIncidentMarkdown_SingleHealthyHPA(t *testing.T) {
	reports := []StatusReport{
		{
			Analysis: Analysis{
				Namespace:   "default",
				Name:        "web-hpa",
				Target:      "Deployment/web",
				Current:     5,
				Desired:     5,
				Min:         2,
				Max:         10,
				Health:      "OK",
				HealthScore: 95,
				Summary:     "HPA is operating normally.",
				Conditions: []Condition{
					{Type: "ScalingActive", Status: "True", Reason: "ValidMetricFound", Message: "the HPA was able to successfully calculate a replica count"},
				},
				Metrics: []Metric{
					{Name: "cpu", Current: "78%", Target: "80%", Ratio: floatPtr(0.975), Text: "cpu 78%/80%"},
				},
			},
		},
	}

	var buf bytes.Buffer
	if err := WriteRichIncidentMarkdown(&buf, reports); err != nil {
		t.Fatalf("WriteRichIncidentMarkdown returned error: %v", err)
	}
	output := buf.String()

	expectedSections := []string{
		"# HPA Incident Report:",
		"## Incident Summary",
		"## Executive Summary",
		"## Affected Workloads",
		"## Remediation Steps",
		"## Recommendations",
		"## Escalation Notes",
		"Generated by kubectl-hpa-status",
	}
	for _, section := range expectedSections {
		if !strings.Contains(output, section) {
			t.Errorf("expected output to contain %q, got:\n%s", section, output)
		}
	}

	if !strings.Contains(output, "web-hpa") {
		t.Error("expected output to contain HPA name web-hpa")
	}
	if !strings.Contains(output, "OK") {
		t.Error("expected output to contain health state OK")
	}
	if !strings.Contains(output, "SEVERITY: LOW") {
		t.Error("expected severity LOW for healthy HPA")
	}
}

func TestWriteRichIncidentMarkdown_SingleUnhealthyHPA(t *testing.T) {
	reports := []StatusReport{
		{
			Analysis: Analysis{
				Namespace:   "prod",
				Name:        "api-hpa",
				Target:      "Deployment/api",
				Current:     10,
				Desired:     10,
				Min:         2,
				Max:         10,
				Health:      "ERROR",
				HealthScore: 30,
				Summary:     "Metrics pipeline unavailable.",
				Conditions: []Condition{
					{Type: "ScalingActive", Status: "False", Reason: "FailedGetResourceMetric", Message: "unable to get metric cpu"},
					{Type: "AbleToScale", Status: "True", Reason: "ReadyForNewScale", Message: "ready for new scale"},
				},
				Metrics: []Metric{},
			},
		},
	}

	var buf bytes.Buffer
	if err := WriteRichIncidentMarkdown(&buf, reports); err != nil {
		t.Fatalf("WriteRichIncidentMarkdown returned error: %v", err)
	}
	output := buf.String()

	if !strings.Contains(output, "## Root Cause Analysis") {
		t.Error("expected Root Cause Analysis section for unhealthy HPA")
	}
	if !strings.Contains(output, "ScalingActive") {
		t.Error("expected condition analysis with ScalingActive")
	}
	if !strings.Contains(output, "SEVERITY: CRITICAL") {
		t.Error("expected severity CRITICAL for ERROR state HPA with score 30")
	}
	if !strings.Contains(output, "FailedGetResourceMetric") {
		t.Error("expected condition reason in root cause analysis")
	}
}

func TestWriteRichIncidentMarkdown_MultipleHPAs(t *testing.T) {
	reports := []StatusReport{
		{
			Analysis: Analysis{
				Namespace:   "default",
				Name:        "web-hpa",
				Target:      "Deployment/web",
				Current:     5,
				Desired:     5,
				Min:         2,
				Max:         10,
				Health:      "OK",
				HealthScore: 95,
				Summary:     "Operating normally.",
			},
		},
		{
			Analysis: Analysis{
				Namespace:   "prod",
				Name:        "api-hpa",
				Target:      "Deployment/api",
				Current:     3,
				Desired:     5,
				Min:         1,
				Max:         20,
				Health:      "LIMITED",
				HealthScore: 75,
				Summary:     "Scaling limited by maxReplicas.",
			},
		},
	}

	var buf bytes.Buffer
	if err := WriteRichIncidentMarkdown(&buf, reports); err != nil {
		t.Fatalf("WriteRichIncidentMarkdown returned error: %v", err)
	}
	output := buf.String()

	if !strings.Contains(output, "web-hpa") {
		t.Error("expected web-hpa in executive summary")
	}
	if !strings.Contains(output, "api-hpa") {
		t.Error("expected api-hpa in executive summary")
	}
	if !strings.Contains(output, "Affected HPAs:** 2") {
		t.Error("expected Affected HPAs: 2")
	}
}

func TestWriteRichIncidentMarkdown_WithEvents(t *testing.T) {
	ts := time.Date(2025, 1, 15, 10, 30, 0, 0, time.UTC)
	reports := []StatusReport{
		{
			Analysis: Analysis{
				Namespace:   "default",
				Name:        "web-hpa",
				Target:      "Deployment/web",
				Current:     5,
				Desired:     7,
				Min:         2,
				Max:         10,
				Health:      "LIMITED",
				HealthScore: 75,
				Summary:     "Scaling in progress.",
			},
			Events: []Event{
				{Reason: "SuccessfulRescale", Message: "New size: 7; reason: cpu utilization above target", Timestamp: ts},
				{Reason: "FailedGetResourceMetric", Message: "unable to get metric cpu: the server could not find the requested resource", Timestamp: ts.Add(-5 * time.Minute)},
			},
		},
	}

	var buf bytes.Buffer
	if err := WriteRichIncidentMarkdown(&buf, reports); err != nil {
		t.Fatalf("WriteRichIncidentMarkdown returned error: %v", err)
	}
	output := buf.String()

	if !strings.Contains(output, "## Timeline of Events") {
		t.Error("expected Timeline of Events section")
	}
	if !strings.Contains(output, "SuccessfulRescale") {
		t.Error("expected SuccessfulRescale event in timeline")
	}
	if !strings.Contains(output, "FailedGetResourceMetric") {
		t.Error("expected FailedGetResourceMetric event in timeline")
	}
}

func TestWriteRichIncidentMarkdown_WithSuggestions(t *testing.T) {
	reports := []StatusReport{
		{
			Analysis: Analysis{
				Namespace:   "default",
				Name:        "web-hpa",
				Target:      "Deployment/web",
				Current:     5,
				Desired:     5,
				Min:         2,
				Max:         10,
				Health:      "LIMITED",
				HealthScore: 75,
				Summary:     "Scaling limited.",
				Suggestions: []Suggestion{
					{
						Title:       "Increase maxReplicas",
						Description: "Consider raising maxReplicas to allow more headroom.",
						Command:     "kubectl patch hpa web-hpa -p '{\"spec\":{\"maxReplicas\":20}}'",
						Risk:        "low",
						Patch:       `{"spec":{"maxReplicas":20}}`,
					},
				},
			},
		},
	}

	var buf bytes.Buffer
	if err := WriteRichIncidentMarkdown(&buf, reports); err != nil {
		t.Fatalf("WriteRichIncidentMarkdown returned error: %v", err)
	}
	output := buf.String()

	if !strings.Contains(output, "Increase maxReplicas") {
		t.Error("expected suggestion title in remediation section")
	}
	if !strings.Contains(output, "kubectl patch") {
		t.Error("expected kubectl command in remediation section")
	}
}

func TestWriteRichIncidentMarkdown_NoOptionalFields(t *testing.T) {
	reports := []StatusReport{
		{
			Analysis: Analysis{
				Namespace:   "default",
				Name:        "minimal-hpa",
				Target:      "Deployment/minimal",
				Health:      "OK",
				HealthScore: 100,
			},
		},
	}

	var buf bytes.Buffer
	if err := WriteRichIncidentMarkdown(&buf, reports); err != nil {
		t.Fatalf("WriteRichIncidentMarkdown returned error: %v", err)
	}
	output := buf.String()

	if !strings.Contains(output, "# HPA Incident Report:") {
		t.Error("expected incident report header")
	}
	if !strings.Contains(output, "minimal-hpa") {
		t.Error("expected HPA name in output")
	}
	if strings.Contains(output, "## Timeline of Events") {
		t.Error("expected no Timeline section when no events are present")
	}
	if strings.Contains(output, "## Capacity Context") {
		t.Error("expected no Capacity Context section when not available")
	}
}

func TestWriteRichIncidentMarkdown_WithChurnAnalysis(t *testing.T) {
	reports := []StatusReport{
		{
			Analysis: Analysis{
				Namespace:   "default",
				Name:        "web-hpa",
				Target:      "Deployment/web",
				Current:     5,
				Desired:     5,
				Min:         2,
				Max:         10,
				Health:      "LIMITED",
				HealthScore: 70,
				Summary:     "Scaling churn detected.",
				ChurnAnalysis: &ChurnAnalysis{
					Score:          65,
					Level:          ChurnHigh,
					ScaleUpCount:   8,
					ScaleDownCount: 7,
					DirectionFlips: 6,
				},
			},
		},
	}

	var buf bytes.Buffer
	if err := WriteRichIncidentMarkdown(&buf, reports); err != nil {
		t.Fatalf("WriteRichIncidentMarkdown returned error: %v", err)
	}
	output := buf.String()

	if !strings.Contains(output, "Churn Detected:") {
		t.Error("expected churn analysis in root cause section")
	}
	if !strings.Contains(output, "HIGH") {
		t.Error("expected churn level HIGH")
	}
}

func TestWriteRichIncidentMarkdown_WithHealthTrendAnomalies(t *testing.T) {
	reports := []StatusReport{
		{
			Analysis: Analysis{
				Namespace:   "default",
				Name:        "web-hpa",
				Target:      "Deployment/web",
				Current:     5,
				Desired:     5,
				Min:         2,
				Max:         10,
				Health:      "ERROR",
				HealthScore: 40,
				Summary:     "Health degrading.",
				HealthTrend: &HealthTrendResult{
					Snapshots: []HealthSnapshot{
						{Timestamp: time.Now().Add(-10 * time.Minute), HealthScore: 90, HealthState: "OK"},
						{Timestamp: time.Now(), HealthScore: 40, HealthState: "ERROR"},
					},
					Variance:         25.0,
					FlappingDetected: true,
					Anomalies: []AnomalyDetection{
						{
							Type:          AnomalySuddenDegradation,
							Severity:      "critical",
							ScoreBefore:   90,
							ScoreAfter:    40,
							CauseEstimate: "Metrics pipeline became unavailable",
							Remediation:   "Check metrics-server availability",
						},
					},
				},
			},
		},
	}

	var buf bytes.Buffer
	if err := WriteRichIncidentMarkdown(&buf, reports); err != nil {
		t.Fatalf("WriteRichIncidentMarkdown returned error: %v", err)
	}
	output := buf.String()

	if !strings.Contains(output, "**Anomaly Detection:**") {
		t.Error("expected anomaly detection in root cause section")
	}
	if !strings.Contains(output, "sudden-degradation") {
		t.Error("expected anomaly type in output")
	}
}

func TestWriteRichIncidentMarkdown_WithCapacityContext(t *testing.T) {
	reports := []StatusReport{
		{
			Analysis: Analysis{
				Namespace:   "default",
				Name:        "web-hpa",
				Target:      "Deployment/web",
				Current:     5,
				Desired:     10,
				Min:         2,
				Max:         10,
				Health:      "LIMITED",
				HealthScore: 75,
				Summary:     "At maxReplicas.",
				CapacityContext: &CapacityContext{
					PendingPods: []PendingPodInfo{
						{Name: "web-abc12", Unschedulable: true, Reasons: []string{"Insufficient cpu"}},
					},
					QuotaConstraints: []QuotaConstraint{
						{Name: "compute", Resource: "requests.cpu", Used: "19", Hard: "20", Message: "Near CPU quota limit"},
					},
					NodeHints: []string{"Consider adding nodes to increase capacity"},
				},
			},
		},
	}

	var buf bytes.Buffer
	if err := WriteRichIncidentMarkdown(&buf, reports); err != nil {
		t.Fatalf("WriteRichIncidentMarkdown returned error: %v", err)
	}
	output := buf.String()

	if !strings.Contains(output, "## Capacity Context") {
		t.Error("expected Capacity Context section")
	}
	if !strings.Contains(output, "Insufficient cpu") {
		t.Error("expected pending pod reason in capacity context")
	}
	if !strings.Contains(output, "Near CPU quota limit") {
		t.Error("expected quota constraint in capacity context")
	}
}

func TestWriteRichIncidentMarkdown_EscalationNotes(t *testing.T) {
	tests := []struct {
		name           string
		health         string
		expectPlatform bool
		expectApp      bool
	}{
		{"ERROR health requires platform team", "ERROR", true, false},
		{"LIMITED health requires application team", "LIMITED", false, true},
		{"OK health no escalation needed", "OK", false, false},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			reports := []StatusReport{
				{
					Analysis: Analysis{
						Namespace:   "default",
						Name:        "test-hpa",
						Target:      "Deployment/test",
						Health:      tc.health,
						HealthScore: 50,
					},
				},
			}

			var buf bytes.Buffer
			if err := WriteRichIncidentMarkdown(&buf, reports); err != nil {
				t.Fatalf("WriteRichIncidentMarkdown returned error: %v", err)
			}
			output := buf.String()

			if tc.expectPlatform && !strings.Contains(output, "platform team") {
				t.Error("expected platform team escalation note")
			}
			if tc.expectApp && !strings.Contains(output, "application team") {
				t.Error("expected application team escalation note")
			}
		})
	}
}

func TestWriteRichIncidentMarkdown_ValidMarkdown(t *testing.T) {
	reports := []StatusReport{
		{
			Analysis: Analysis{
				Namespace:   "default",
				Name:        "web-hpa",
				Target:      "Deployment/web",
				Current:     5,
				Desired:     5,
				Min:         2,
				Max:         10,
				Health:      "OK",
				HealthScore: 95,
				Summary:     "Operating normally.",
				Conditions: []Condition{
					{Type: "ScalingActive", Status: "True", Reason: "ValidMetricFound", Message: "the HPA was able to successfully calculate a replica count"},
				},
				Metrics: []Metric{
					{Name: "cpu", Current: "78%", Target: "80%", Ratio: floatPtr(0.975), Text: "cpu 78%/80%"},
				},
			},
			Events: []Event{
				{Reason: "SuccessfulRescale", Message: "New size: 5", Timestamp: time.Now()},
			},
		},
	}

	var buf bytes.Buffer
	if err := WriteRichIncidentMarkdown(&buf, reports); err != nil {
		t.Fatalf("WriteRichIncidentMarkdown returned error: %v", err)
	}
	output := buf.String()

	if strings.Contains(output, "||") {
		t.Error("output should not contain unescaped double pipes")
	}
	lines := strings.Split(output, "\n")
	for i, line := range lines {
		if strings.HasPrefix(line, "|") && strings.HasSuffix(line, "|") {
			parts := strings.Split(line, "|")
			if len(parts) > 2 {
				for _, cell := range parts[1 : len(parts)-1] {
					if strings.Contains(cell, "|") && !strings.Contains(cell, "\\|") {
						t.Errorf("line %d has unescaped pipe in table cell: %q", i, line)
					}
				}
			}
		}
	}
}

func TestWriteRichIncidentMarkdown_EmptyReports(t *testing.T) {
	var buf bytes.Buffer
	err := WriteRichIncidentMarkdown(&buf, []StatusReport{})
	if err != nil {
		t.Fatalf("WriteRichIncidentMarkdown returned error: %v", err)
	}
	output := buf.String()

	if !strings.Contains(output, "# HPA Incident Report") {
		t.Error("expected incident report header even for empty reports")
	}
	if !strings.Contains(output, "No HPAs to report") {
		t.Error("expected empty report message")
	}
}

func TestWriteRichIncidentMarkdown_WithMetricsDiagnostics(t *testing.T) {
	reports := []StatusReport{
		{
			Analysis: Analysis{
				Namespace:   "default",
				Name:        "web-hpa",
				Target:      "Deployment/web",
				Current:     5,
				Desired:     5,
				Min:         2,
				Max:         10,
				Health:      "ERROR",
				HealthScore: 50,
				Summary:     "Metrics pipeline degraded.",
				MetricsDiagnostics: &MetricsPipelineDiagnostics{
					OverallStatus: "error",
					PerMetricChecks: []PerMetricHealthCheck{
						{MetricType: "Resource", MetricName: "cpu", Status: "missing", Details: "No current data", Remediation: "Check metrics-server"},
					},
				},
			},
		},
	}

	var buf bytes.Buffer
	if err := WriteRichIncidentMarkdown(&buf, reports); err != nil {
		t.Fatalf("WriteRichIncidentMarkdown returned error: %v", err)
	}
	output := buf.String()

	if !strings.Contains(output, "**Metrics Pipeline:**") {
		t.Error("expected metrics pipeline status in root cause section")
	}
	if !strings.Contains(output, "missing") {
		t.Error("expected per-metric check status")
	}
}

func TestWriteRichIncidentMarkdown_SeverityAssessment(t *testing.T) {
	tests := []struct {
		health   string
		score    int
		expected string
	}{
		{"OK", 100, "LOW"},
		{"STABILIZED", 90, "LOW"},
		{"LIMITED", 75, "MEDIUM"},
		{"ERROR", 50, "HIGH"},
		{"ERROR", 20, "CRITICAL"},
	}

	for _, tc := range tests {
		t.Run(tc.health+"_"+string(rune(tc.score+'0')), func(t *testing.T) {
			reports := []StatusReport{
				{
					Analysis: Analysis{
						Name:        "test",
						Namespace:   "default",
						Target:      "Deployment/test",
						Health:      tc.health,
						HealthScore: tc.score,
					},
				},
			}
			var buf bytes.Buffer
			if err := WriteRichIncidentMarkdown(&buf, reports); err != nil {
				t.Fatalf("WriteRichIncidentMarkdown returned error: %v", err)
			}
			if !strings.Contains(buf.String(), "SEVERITY: "+tc.expected) {
				t.Errorf("expected SEVERITY: %s for health=%s score=%d, got:\n%s", tc.expected, tc.health, tc.score, buf.String())
			}
		})
	}
}

// floatPtr is a test helper that returns a pointer to the given float64.
func floatPtr(v float64) *float64 {
	return &v
}
