package hpa

import (
	"fmt"
	"io"
	"sort"
	"strings"
	"time"
)

// WriteRichIncidentMarkdown generates a comprehensive incident report in
// Markdown format from one or more StatusReports. The report includes
// incident summary, executive summary table, timeline, root cause analysis,
// affected workloads, remediation steps, capacity context, recommendations,
// and escalation notes.
func WriteRichIncidentMarkdown(out io.Writer, reports []StatusReport) error {
	var buf strings.Builder
	current := now().UTC()

	// Derive a short title from HPA names.
	names := incidentReportNames(reports)

	// --- 1. Incident Summary ---
	buf.WriteString("# HPA Incident Report: ")
	buf.WriteString(names)
	buf.WriteString("\n\n")

	severity := overallSeverity(reports)
	buf.WriteString("## Incident Summary\n\n")
	buf.WriteString(fmt.Sprintf("- **Generated:** %s\n", current.Format(time.RFC3339)))
	buf.WriteString(fmt.Sprintf("- **Severity:** SEVERITY: %s\n", severity))
	buf.WriteString(fmt.Sprintf("- **Affected HPAs:** %d\n", len(reports)))

	if len(reports) == 0 {
		buf.WriteString("\nNo HPAs to report.\n")
		buf.WriteString("\n---\nGenerated by kubectl-hpa-status\n")
		_, err := io.WriteString(out, buf.String())
		return err
	}
	buf.WriteString("\n")

	// --- 2. Executive Summary Table ---
	writeIncidentExecutiveSummary(&buf, reports)

	// --- 3. Timeline of Events ---
	writeIncidentTimeline(&buf, reports)

	// --- 4. Root Cause Analysis ---
	writeIncidentRootCause(&buf, reports)

	// --- 5. Affected Workloads ---
	writeIncidentAffectedWorkloads(&buf, reports)

	// --- 6. Remediation Steps ---
	writeIncidentRemediationSteps(&buf, reports)

	// --- 7. Capacity Context ---
	writeIncidentCapacityContext(&buf, reports)

	// --- 8. Recommendations ---
	writeIncidentRecommendations(&buf, reports)

	// --- 9. Escalation Notes ---
	writeIncidentEscalationNotes(&buf, reports)

	buf.WriteString("---\nGenerated by kubectl-hpa-status\n")

	_, err := io.WriteString(out, buf.String())
	return err
}

// writeIncidentExecutiveSummary renders the per-HPA summary table.
func writeIncidentExecutiveSummary(buf *strings.Builder, reports []StatusReport) {
	buf.WriteString("## Executive Summary\n\n")
	buf.WriteString("| Namespace | Name | Health | Score | Current | Desired | Min | Max |\n")
	buf.WriteString("|-----------|------|--------|-------|---------|---------|-----|-----|\n")
	for _, r := range reports {
		a := r.Analysis
		buf.WriteString(fmt.Sprintf("| %s | %s | %s | %d | %d | %d | %d | %d |\n",
			escapeMarkdown(a.Namespace),
			escapeMarkdown(a.Name),
			severityPrefix(a.Health),
			a.HealthScore,
			a.Current,
			a.Desired,
			a.Min,
			a.Max,
		))
	}
	buf.WriteString("\n")
}

// writeIncidentTimeline renders the events timeline when any report has events.
func writeIncidentTimeline(buf *strings.Builder, reports []StatusReport) {
	hasEvents := false
	for _, r := range reports {
		if len(r.Events) > 0 {
			hasEvents = true
			break
		}
	}
	if !hasEvents {
		return
	}
	buf.WriteString("## Timeline of Events\n\n")
	for _, r := range reports {
		if len(r.Events) == 0 {
			continue
		}
		a := r.Analysis
		buf.WriteString(fmt.Sprintf("### %s/%s\n\n", a.Namespace, a.Name))
		buf.WriteString("| Timestamp | Reason | Message |\n")
		buf.WriteString("|-----------|--------|--------|\n")
		sorted := make([]Event, len(r.Events))
		copy(sorted, r.Events)
		sort.Slice(sorted, func(i, j int) bool {
			return sorted[i].Timestamp.Before(sorted[j].Timestamp)
		})
		for _, e := range sorted {
			ts := ""
			if !e.Timestamp.IsZero() {
				ts = e.Timestamp.Format(time.RFC3339)
			}
			buf.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				ts,
				escapeMarkdown(e.Reason),
				escapeMarkdown(e.Message),
			))
		}
		buf.WriteString("\n")
	}
}

// writeIncidentRootCause renders the root cause analysis section per HPA.
func writeIncidentRootCause(buf *strings.Builder, reports []StatusReport) {
	buf.WriteString("## Root Cause Analysis\n\n")
	for _, r := range reports {
		a := r.Analysis
		buf.WriteString(fmt.Sprintf("### %s/%s\n\n", a.Namespace, a.Name))

		writeRootCauseConditions(buf, a)
		writeRootCauseMetricsPipeline(buf, a)
		writeRootCauseChurn(buf, a)
		writeRootCauseAnomalies(buf, a)

		// If no specific analysis was available, emit the summary.
		if len(a.Conditions) == 0 && a.MetricsDiagnostics == nil && a.ChurnAnalysis == nil && a.HealthTrend == nil {
			if a.Summary != "" {
				buf.WriteString(fmt.Sprintf("%s\n\n", a.Summary))
			} else {
				buf.WriteString("No detailed root cause data available.\n\n")
			}
		}
	}
}

// writeRootCauseConditions renders the Conditions subsection of root cause.
func writeRootCauseConditions(buf *strings.Builder, a Analysis) {
	if len(a.Conditions) == 0 {
		return
	}
	buf.WriteString("**Conditions:**\n\n")
	for _, c := range a.Conditions {
		implication := conditionImplication(c)
		buf.WriteString(fmt.Sprintf("- **%s** (%s): %s — %s\n",
			c.Type, c.Status, escapeMarkdown(c.Reason), implication))
	}
	buf.WriteString("\n")
}

// writeRootCauseMetricsPipeline renders the metrics pipeline diagnostics subsection.
func writeRootCauseMetricsPipeline(buf *strings.Builder, a Analysis) {
	if a.MetricsDiagnostics == nil {
		return
	}
	buf.WriteString(fmt.Sprintf("**Metrics Pipeline:** %s\n\n", a.MetricsDiagnostics.OverallStatus))
	for _, check := range a.MetricsDiagnostics.PerMetricChecks {
		buf.WriteString(fmt.Sprintf("- %s/%s: %s — %s\n",
			check.MetricType, check.MetricName, check.Status, escapeMarkdown(check.Details)))
	}
	if len(a.MetricsDiagnostics.RemediationSteps) > 0 {
		buf.WriteString("\n**Remediation Steps:**\n\n")
		for _, step := range a.MetricsDiagnostics.RemediationSteps {
			buf.WriteString(fmt.Sprintf("- %s\n", step))
		}
	}
	buf.WriteString("\n")
}

// writeRootCauseChurn renders the churn analysis subsection.
func writeRootCauseChurn(buf *strings.Builder, a Analysis) {
	if a.ChurnAnalysis == nil {
		return
	}
	ca := a.ChurnAnalysis
	buf.WriteString(fmt.Sprintf("**Churn Detected:** level=%s score=%d flips=%d (scale-ups=%d scale-downs=%d)\n\n",
		ca.Level, ca.Score, ca.DirectionFlips, ca.ScaleUpCount, ca.ScaleDownCount))
	for _, rec := range ca.Recommendations {
		buf.WriteString(fmt.Sprintf("- **%s:** change %s -> %s — %s\n",
			rec.Type, rec.CurrentValue, rec.RecommendedValue, rec.Rationale))
	}
	buf.WriteString("\n")
}

// writeRootCauseAnomalies renders the health-trend anomaly subsection.
func writeRootCauseAnomalies(buf *strings.Builder, a Analysis) {
	if a.HealthTrend == nil || len(a.HealthTrend.Anomalies) == 0 {
		return
	}
	buf.WriteString("**Anomaly Detection:**\n\n")
	for _, anomaly := range a.HealthTrend.Anomalies {
		buf.WriteString(fmt.Sprintf("- **%s** (severity: %s): score changed %d -> %d",
			anomaly.Type, anomaly.Severity, anomaly.ScoreBefore, anomaly.ScoreAfter))
		if anomaly.CauseEstimate != "" {
			buf.WriteString(fmt.Sprintf("\n  - Cause: %s", anomaly.CauseEstimate))
		}
		if anomaly.Remediation != "" {
			buf.WriteString(fmt.Sprintf("\n  - Remediation: %s", anomaly.Remediation))
		}
		buf.WriteString("\n")
	}
	if a.HealthTrend.FlappingDetected {
		buf.WriteString(fmt.Sprintf("- **Flapping detected** (variance: %.1f)\n", a.HealthTrend.Variance))
	}
	buf.WriteString("\n")
}

// writeIncidentAffectedWorkloads renders the affected workloads section per HPA.
func writeIncidentAffectedWorkloads(buf *strings.Builder, reports []StatusReport) {
	buf.WriteString("## Affected Workloads\n\n")
	for _, r := range reports {
		a := r.Analysis
		buf.WriteString(fmt.Sprintf("### %s/%s\n\n", a.Namespace, a.Name))
		buf.WriteString(fmt.Sprintf("- **Target:** %s\n", a.Target))
		buf.WriteString(fmt.Sprintf("- **Replicas:** current=%d desired=%d min=%d max=%d\n",
			a.Current, a.Desired, a.Min, a.Max))
		if a.TargetReplicas != nil {
			tr := a.TargetReplicas
			buf.WriteString(fmt.Sprintf("- **Scale Target Replicas:** total=%d ready=%d notReady=%d",
				tr.TotalReplicas, tr.ReadyReplicas, tr.NotReady))
			if tr.Pending > 0 {
				buf.WriteString(fmt.Sprintf(" pending=%d", tr.Pending))
			}
			if tr.Unschedulable > 0 {
				buf.WriteString(fmt.Sprintf(" unschedulable=%d", tr.Unschedulable))
			}
			buf.WriteString("\n")
		}

		// Metrics context
		if len(a.Metrics) > 0 {
			buf.WriteString("- **Metrics:**\n")
			for _, m := range a.Metrics {
				name := m.Name
				if name == "" {
					name = m.Type
				}
				buf.WriteString(fmt.Sprintf("  - %s: %s / %s", name, m.Current, m.Target))
				if m.Ratio != nil {
					buf.WriteString(fmt.Sprintf(" (ratio: %.3f)", *m.Ratio))
				}
				buf.WriteString("\n")
			}
		}
		buf.WriteString("\n")
	}
}

// writeIncidentRemediationSteps renders the remediation steps ordered by health severity.
func writeIncidentRemediationSteps(buf *strings.Builder, reports []StatusReport) {
	buf.WriteString("## Remediation Steps\n\n")
	// Collect all remediation items ordered by health severity.
	orderedReports := make([]StatusReport, len(reports))
	copy(orderedReports, reports)
	sort.Slice(orderedReports, func(i, j int) bool {
		return healthPriority(orderedReports[i].Analysis.Health) < healthPriority(orderedReports[j].Analysis.Health)
	})

	stepNum := 1
	for _, r := range orderedReports {
		a := r.Analysis

		// Suggestions first
		for _, s := range a.Suggestions {
			buf.WriteString(fmt.Sprintf("%d. **[%s/%s] %s**: %s\n",
				stepNum, a.Namespace, a.Name, s.Title, s.Description))
			if s.Command != "" {
				buf.WriteString(fmt.Sprintf("   ```\n   %s\n   ```\n", s.Command))
			}
			if s.Risk != "" {
				buf.WriteString(fmt.Sprintf("   - Risk: %s\n", s.Risk))
			}
			if s.Patch != "" {
				buf.WriteString(fmt.Sprintf("   - Patch: `%s`\n", s.Patch))
			}
			stepNum++
		}

		// Actions as fallback
		if len(a.Suggestions) == 0 && len(a.Actions) > 0 {
			for _, action := range a.Actions {
				buf.WriteString(fmt.Sprintf("%d. **[%s/%s]** %s\n",
					stepNum, a.Namespace, a.Name, action))
				stepNum++
			}
		}
	}

	if stepNum == 1 {
		buf.WriteString("No specific remediation steps identified.\n")
	}
	buf.WriteString("\n")
}

// writeIncidentCapacityContext renders the capacity context section when present.
func writeIncidentCapacityContext(buf *strings.Builder, reports []StatusReport) {
	if !anyReportHasCapacity(reports) {
		return
	}
	buf.WriteString("## Capacity Context\n\n")
	for _, r := range reports {
		writeIncidentReportCapacity(buf, r.Analysis)
	}
}

// anyReportHasCapacity reports whether any report carries pending pods, quota constraints, node hints, or capacity headroom.
func anyReportHasCapacity(reports []StatusReport) bool {
	for _, r := range reports {
		if r.Analysis.CapacityContext != nil {
			cc := r.Analysis.CapacityContext
			if len(cc.PendingPods) > 0 || len(cc.QuotaConstraints) > 0 || len(cc.NodeHints) > 0 {
				return true
			}
		}
		if r.Analysis.CapacityHeadroom != nil {
			return true
		}
	}
	return false
}

// writeIncidentReportCapacity renders the capacity context and headroom subsections for a single report.
func writeIncidentReportCapacity(buf *strings.Builder, a Analysis) {
	wroteHeader := false

	if a.CapacityContext != nil {
		cc := a.CapacityContext
		if len(cc.PendingPods) > 0 || len(cc.QuotaConstraints) > 0 || len(cc.NodeHints) > 0 {
			buf.WriteString(fmt.Sprintf("### %s/%s\n\n", a.Namespace, a.Name))
			wroteHeader = true

			writeIncidentPendingPods(buf, cc.PendingPods)
			writeIncidentQuotaConstraints(buf, cc.QuotaConstraints)
			writeIncidentNodeHints(buf, cc.NodeHints)
		}
	}

	if a.CapacityHeadroom != nil {
		writeIncidentCapacityHeadroom(buf, a, wroteHeader)
	}
}

func writeIncidentPendingPods(buf *strings.Builder, pods []PendingPodInfo) {
	if len(pods) == 0 {
		return
	}
	buf.WriteString("**Pending Pods:**\n\n")
	for _, p := range pods {
		status := "scheduled"
		if p.Unschedulable {
			status = "unschedulable"
		}
		buf.WriteString(fmt.Sprintf("- %s (%s): %s\n",
			p.Name, status, escapeMarkdown(strings.Join(p.Reasons, "; "))))
	}
	buf.WriteString("\n")
}

func writeIncidentQuotaConstraints(buf *strings.Builder, quotas []QuotaConstraint) {
	if len(quotas) == 0 {
		return
	}
	buf.WriteString("**Resource Quotas:**\n\n")
	for _, q := range quotas {
		buf.WriteString(fmt.Sprintf("- %s/%s: used=%s hard=%s — %s\n",
			q.Name, q.Resource, q.Used, q.Hard, q.Message))
	}
	buf.WriteString("\n")
}

func writeIncidentNodeHints(buf *strings.Builder, hints []string) {
	if len(hints) == 0 {
		return
	}
	buf.WriteString("**Hints:**\n\n")
	for _, hint := range hints {
		buf.WriteString(fmt.Sprintf("- %s\n", hint))
	}
	buf.WriteString("\n")
}

func writeIncidentCapacityHeadroom(buf *strings.Builder, a Analysis, wroteHeader bool) {
	if !wroteHeader {
		buf.WriteString(fmt.Sprintf("### %s/%s\n\n", a.Namespace, a.Name))
	}
	ch := a.CapacityHeadroom
	buf.WriteString(fmt.Sprintf("**Capacity Headroom:** %s (risk: %s)\n",
		ch.ClusterSchedulableHeadroom, ch.Risk))
	if len(ch.Evidence) > 0 {
		for _, e := range ch.Evidence {
			buf.WriteString(fmt.Sprintf("- %s\n", e))
		}
	}
	buf.WriteString("\n")
}

// writeIncidentRecommendations renders the recommendations section.
func writeIncidentRecommendations(buf *strings.Builder, reports []StatusReport) {
	buf.WriteString("## Recommendations\n\n")
	recNum := 1
	hasRecs := false
	for _, r := range reports {
		a := r.Analysis

		// Churn recommendations
		if a.ChurnAnalysis != nil && len(a.ChurnAnalysis.Recommendations) > 0 {
			for _, rec := range a.ChurnAnalysis.Recommendations {
				buf.WriteString(fmt.Sprintf("%d. **%s**: Change %s to %s — %s\n",
					recNum, rec.Type, rec.CurrentValue, rec.RecommendedValue, rec.Rationale))
				recNum++
				hasRecs = true
			}
		}

		// Behavior tuning
		if a.BehaviorAdvisor != nil && len(a.BehaviorAdvisor.Findings) > 0 {
			for _, f := range a.BehaviorAdvisor.Findings {
				buf.WriteString(fmt.Sprintf("%d. **%s**: %s\n", recNum, f.Category, f.Message))
				recNum++
				hasRecs = true
			}
		}

		// Interpretation as long-term advice
		if len(a.Interpretation) > 0 {
			for _, line := range a.Interpretation {
				buf.WriteString(fmt.Sprintf("%d. %s\n", recNum, line))
				recNum++
				hasRecs = true
			}
		}
	}
	if !hasRecs {
		buf.WriteString("No additional recommendations at this time.\n")
	}
	buf.WriteString("\n")
}

// writeIncidentEscalationNotes renders the escalation notes section.
func writeIncidentEscalationNotes(buf *strings.Builder, reports []StatusReport) {
	buf.WriteString("## Escalation Notes\n\n")
	escalationWritten := false
	for _, r := range reports {
		a := r.Analysis
		switch a.Health {
		case string(HealthError):
			buf.WriteString(fmt.Sprintf("- **%s/%s**: Escalate to **platform team** — metrics pipeline or HPA controller may be unavailable.\n",
				a.Namespace, a.Name))
			escalationWritten = true
		case string(HealthLimited):
			buf.WriteString(fmt.Sprintf("- **%s/%s**: Escalate to **application team** — HPA is capped; review scaling limits and workload configuration.\n",
				a.Namespace, a.Name))
			escalationWritten = true
		}
	}
	if !escalationWritten {
		buf.WriteString("No immediate escalation required. All HPAs are healthy.\n")
	}
	buf.WriteString("\n")
}

// overallSeverity computes the highest severity across all reports.
func overallSeverity(reports []StatusReport) string {
	if len(reports) == 0 {
		return "NONE"
	}
	worst := "LOW"
	for _, r := range reports {
		s := healthSeverity(r.Analysis.Health, r.Analysis.HealthScore)
		if severityHigher(s, worst) {
			worst = s
		}
	}
	return worst
}

// healthSeverity maps health state and score to a severity label.
func healthSeverity(health string, score int) string {
	switch {
	case health == string(HealthError) && score <= 30:
		return "CRITICAL"
	case health == string(HealthError):
		return "HIGH"
	case health == string(HealthLimited):
		return "MEDIUM"
	default:
		return "LOW"
	}
}

// severityHigher returns true if a is more severe than b.
func severityHigher(a, b string) bool {
	order := map[string]int{"CRITICAL": 4, "HIGH": 3, "MEDIUM": 2, "LOW": 1, "NONE": 0}
	return order[a] > order[b]
}

// severityPrefix prefixes a visual marker for the health state.
func severityPrefix(health string) string {
	switch health {
	case string(HealthError):
		return "[ALERT] " + health
	case string(HealthLimited):
		return "[WARN] " + health
	case string(HealthStabilized):
		return "[INFO] " + health
	default:
		return "[OK] " + health
	}
}

// healthPriority returns a numeric priority for ordering (lower = more urgent).
func healthPriority(health string) int {
	switch health {
	case string(HealthError):
		return 0
	case string(HealthLimited):
		return 1
	case string(HealthStabilized):
		return 2
	default:
		return 3
	}
}

// conditionImplication returns a human-readable explanation for a condition.
func conditionImplication(c Condition) string {
	switch {
	case c.Type == ConditionScalingActive && c.Status != "True":
		return "Metrics pipeline is not providing data; HPA cannot make scaling decisions."
	case c.Type == ConditionAbleToScale && c.Status != "True":
		return "HPA controller cannot act on scaling decisions (check RBAC or scaleTargetRef)."
	case c.Type == ConditionScalingLimited && c.Status == "True":
		return "HPA is capped by minReplicas or maxReplicas."
	default:
		if c.Message != "" {
			return c.Message
		}
		return "No specific implication."
	}
}

// incidentReportNames builds a comma-separated list of HPA names for the title.
func incidentReportNames(reports []StatusReport) string {
	if len(reports) == 0 {
		return "no-hpas"
	}
	if len(reports) == 1 {
		a := reports[0].Analysis
		return fmt.Sprintf("%s/%s", a.Namespace, a.Name)
	}
	names := make([]string, len(reports))
	for i, r := range reports {
		names[i] = fmt.Sprintf("%s/%s", r.Analysis.Namespace, r.Analysis.Name)
	}
	return strings.Join(names, ", ")
}
