package hpa

import (
	"bytes"
	"strings"
	"testing"
)

func sampleStatusReport() StatusReport {
	ratio := 0.975
	return StatusReport{
		Analysis: Analysis{
			Namespace:   "default",
			Name:        "web-hpa",
			Target:      "Deployment/web",
			Current:     5,
			Desired:     5,
			Min:         2,
			Max:         10,
			Health:      "OK",
			HealthScore: 95,
			Summary:     "HPA is operating normally.",
			Conditions: []Condition{
				{Type: "ScalingActive", Status: "True", Reason: "ValidMetricFound", Message: "the HPA was able to successfully calculate a replica count"},
				{Type: "AbleToScale", Status: "True", Reason: "ReadyForNewScale", Message: "recommended size matches current size"},
			},
			Metrics: []Metric{
				{Name: "cpu", Current: "78%", Target: "80%", Ratio: &ratio, Text: "cpu 78%/80%"},
			},
			Actions: []string{
				"No immediate action required.",
			},
			Suggestions: []Suggestion{
				{Title: "Increase maxReplicas", Description: "Consider raising maxReplicas to allow more headroom.", Command: "kubectl patch hpa web-hpa -p '{\"spec\":{\"maxReplicas\":20}}'", Risk: "low"},
			},
		},
		Events: []Event{
			{Reason: "SuccessfulRescale", Message: "New size: 5; reason: cpu resource utilization"},
		},
	}
}

func TestWriteMarkdownReportContainsHeaders(t *testing.T) {
	report := sampleStatusReport()
	var buf bytes.Buffer
	if err := WriteMarkdownReport(&buf, report); err != nil {
		t.Fatalf("WriteMarkdownReport returned error: %v", err)
	}
	output := buf.String()

	expectedHeaders := []string{
		"# HPA Status Report: web-hpa (default)",
		"**Target:** Deployment/web",
		"**Health:** OK (95/100)",
		"**Replicas:** current=5 desired=5 min=2 max=10",
		"## Summary",
		"## Conditions",
		"| Type | Status | Reason | Message |",
		"## Metrics",
		"| Metric | Current | Target | Ratio |",
		"## Recommendations",
		"## Suggestions",
		"## Events",
		"Generated by kubectl-hpa-status",
	}

	for _, header := range expectedHeaders {
		if !strings.Contains(output, header) {
			t.Errorf("expected output to contain %q, got:\n%s", header, output)
		}
	}
}

func TestWriteMarkdownReportMetricRatio(t *testing.T) {
	report := sampleStatusReport()
	var buf bytes.Buffer
	if err := WriteMarkdownReport(&buf, report); err != nil {
		t.Fatalf("WriteMarkdownReport returned error: %v", err)
	}
	output := buf.String()

	if !strings.Contains(output, "| cpu | 78% | 80% | 0.975 |") {
		t.Errorf("expected cpu metric row with ratio 0.975, got:\n%s", output)
	}
}

func TestWriteMarkdownReportEmptyFields(t *testing.T) {
	report := StatusReport{
		Analysis: Analysis{
			Namespace:   "default",
			Name:        "empty-hpa",
			Health:      "OK",
			HealthScore: 0,
		},
	}
	var buf bytes.Buffer
	if err := WriteMarkdownReport(&buf, report); err != nil {
		t.Fatalf("WriteMarkdownReport returned error: %v", err)
	}
	output := buf.String()

	if !strings.Contains(output, "_No summary available._") {
		t.Errorf("expected empty summary placeholder, got:\n%s", output)
	}
	if !strings.Contains(output, "_No conditions reported._") {
		t.Errorf("expected empty conditions placeholder, got:\n%s", output)
	}
	if !strings.Contains(output, "_No current metrics reported._") {
		t.Errorf("expected empty metrics placeholder, got:\n%s", output)
	}
}

func TestWriteMarkdownReportEscapesPipes(t *testing.T) {
	report := StatusReport{
		Analysis: Analysis{
			Namespace: "default",
			Name:      "pipe-test",
			Target:    "Deployment/svc|web",
			Conditions: []Condition{
				{Type: "ScalingActive", Status: "True", Reason: "OK", Message: "metric | pipe"},
			},
		},
	}
	var buf bytes.Buffer
	if err := WriteMarkdownReport(&buf, report); err != nil {
		t.Fatalf("WriteMarkdownReport returned error: %v", err)
	}
	output := buf.String()

	if strings.Contains(output, "metric | pipe") {
		t.Errorf("expected pipe to be escaped in conditions table, got:\n%s", output)
	}
	if !strings.Contains(output, `metric \| pipe`) {
		t.Errorf("expected escaped pipe in conditions table, got:\n%s", output)
	}
}

func TestWriteHTMLReportHasStructure(t *testing.T) {
	report := sampleStatusReport()
	var buf bytes.Buffer
	if err := WriteHTMLReport(&buf, report); err != nil {
		t.Fatalf("WriteHTMLReport returned error: %v", err)
	}
	output := buf.String()

	if !strings.HasPrefix(output, "<!DOCTYPE html>") {
		t.Errorf("expected HTML to start with DOCTYPE, got:\n%s", output[:50])
	}
	if !strings.Contains(output, "</html>") {
		t.Errorf("expected closing </html> tag, got:\n%s", output)
	}
	if !strings.Contains(output, "<head>") {
		t.Errorf("expected <head> tag, got:\n%s", output)
	}
	if !strings.Contains(output, "</head>") {
		t.Errorf("expected </head> tag, got:\n%s", output)
	}
	if !strings.Contains(output, "<body>") {
		t.Errorf("expected <body> tag, got:\n%s", output)
	}
	if !strings.Contains(output, "</body>") {
		t.Errorf("expected </body> tag, got:\n%s", output)
	}
	if !strings.Contains(output, "<style>") {
		t.Errorf("expected <style> tag for inline CSS, got:\n%s", output)
	}
}

func TestWriteHTMLReportContainsContent(t *testing.T) {
	report := sampleStatusReport()
	var buf bytes.Buffer
	if err := WriteHTMLReport(&buf, report); err != nil {
		t.Fatalf("WriteHTMLReport returned error: %v", err)
	}
	output := buf.String()

	expectedFragments := []string{
		"web-hpa",
		"Deployment/web",
		"health-ok",
		"current=5 desired=5 min=2 max=10",
		"ScalingActive",
		"ValidMetricFound",
		"<td>78%</td>",
		"<td>80%</td>",
		"0.975",
		"Increase maxReplicas",
		"No immediate action required.",
		"Generated by kubectl-hpa-status",
	}

	for _, frag := range expectedFragments {
		if !strings.Contains(output, frag) {
			t.Errorf("expected HTML to contain %q, got:\n%s", frag, output)
		}
	}
}

func TestWriteHTMLReportHealthColorCoding(t *testing.T) {
	tests := []struct {
		health string
		class  string
	}{
		{"OK", "health-ok"},
		{"ERROR", "health-error"},
		{"LIMITED", "health-limited"},
		{"STABILIZED", "health-stabilized"},
	}

	for _, tc := range tests {
		t.Run(tc.health, func(t *testing.T) {
			report := StatusReport{
				Analysis: Analysis{
					Name:         "test",
					Health:       tc.health,
					HealthScore:  50,
				},
			}
			var buf bytes.Buffer
			if err := WriteHTMLReport(&buf, report); err != nil {
				t.Fatalf("WriteHTMLReport returned error: %v", err)
			}
			if !strings.Contains(buf.String(), tc.class) {
				t.Errorf("expected health class %q in HTML output", tc.class)
			}
		})
	}
}

func TestWriteHTMLReportEmptyFields(t *testing.T) {
	report := StatusReport{
		Analysis: Analysis{
			Namespace: "default",
			Name:      "empty-hpa",
		},
	}
	var buf bytes.Buffer
	if err := WriteHTMLReport(&buf, report); err != nil {
		t.Fatalf("WriteHTMLReport returned error: %v", err)
	}
	output := buf.String()

	if !strings.Contains(output, "<em>No conditions reported.</em>") {
		t.Errorf("expected empty conditions placeholder, got:\n%s", output)
	}
	if !strings.Contains(output, "<em>No current metrics reported.</em>") {
		t.Errorf("expected empty metrics placeholder, got:\n%s", output)
	}
}

func TestWriteMarkdownListReport(t *testing.T) {
	report := ListReport{
		Items: []ListItem{
			{
				Namespace:   "default",
				Name:        "web-hpa",
				Target:      "Deployment/web",
				Current:     5,
				Desired:     5,
				Min:         2,
				Max:         10,
				Health:      "OK",
				HealthScore: 95,
				Summary:     "Operating normally.",
			},
			{
				Namespace:   "prod",
				Name:        "api-hpa",
				Target:      "Deployment/api",
				Current:     3,
				Desired:     5,
				Min:         1,
				Max:         20,
				Health:      "LIMITED",
				HealthScore: 75,
				Summary:     "Scaling limited.",
			},
		},
	}
	var buf bytes.Buffer
	if err := WriteMarkdownListReport(&buf, report); err != nil {
		t.Fatalf("WriteMarkdownListReport returned error: %v", err)
	}
	output := buf.String()

	if !strings.Contains(output, "# HPA List Report") {
		t.Errorf("expected list report header, got:\n%s", output)
	}
	if !strings.Contains(output, "| default | web-hpa |") {
		t.Errorf("expected default/web-hpa row, got:\n%s", output)
	}
	if !strings.Contains(output, "| prod | api-hpa |") {
		t.Errorf("expected prod/api-hpa row, got:\n%s", output)
	}
	if !strings.Contains(output, "Generated by kubectl-hpa-status") {
		t.Errorf("expected footer, got:\n%s", output)
	}
}

func TestWriteMarkdownListReportEmpty(t *testing.T) {
	report := ListReport{}
	var buf bytes.Buffer
	if err := WriteMarkdownListReport(&buf, report); err != nil {
		t.Fatalf("WriteMarkdownListReport returned error: %v", err)
	}
	output := buf.String()

	if !strings.Contains(output, "_No HPAs found._") {
		t.Errorf("expected empty list placeholder, got:\n%s", output)
	}
}

func TestWriteHTMLListReport(t *testing.T) {
	report := ListReport{
		Items: []ListItem{
			{
				Namespace:   "default",
				Name:        "web-hpa",
				Target:      "Deployment/web",
				Current:     5,
				Desired:     5,
				Min:         2,
				Max:         10,
				Health:      "OK",
				HealthScore: 95,
				Summary:     "Operating normally.",
			},
		},
	}
	var buf bytes.Buffer
	if err := WriteHTMLListReport(&buf, report); err != nil {
		t.Fatalf("WriteHTMLListReport returned error: %v", err)
	}
	output := buf.String()

	if !strings.HasPrefix(output, "<!DOCTYPE html>") {
		t.Errorf("expected HTML to start with DOCTYPE")
	}
	if !strings.Contains(output, "</html>") {
		t.Errorf("expected closing </html> tag")
	}
	if !strings.Contains(output, "<h1>HPA List Report</h1>") {
		t.Errorf("expected list report heading")
	}
	if !strings.Contains(output, "web-hpa") {
		t.Errorf("expected web-hpa in output")
	}
	if !strings.Contains(output, "health-ok") {
		t.Errorf("expected health-ok class in output")
	}
	if !strings.Contains(output, "Generated by kubectl-hpa-status") {
		t.Errorf("expected footer")
	}
}

func TestWriteHTMLListReportEmpty(t *testing.T) {
	report := ListReport{}
	var buf bytes.Buffer
	if err := WriteHTMLListReport(&buf, report); err != nil {
		t.Fatalf("WriteHTMLListReport returned error: %v", err)
	}
	output := buf.String()

	if !strings.Contains(output, "<em>No HPAs found.</em>") {
		t.Errorf("expected empty list placeholder, got:\n%s", output)
	}
}

func TestHTMLEscape(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"hello", "hello"},
		{"<script>", "&lt;script&gt;"},
		{"a & b", "a &amp; b"},
		{`"quoted"`, "&quot;quoted&quot;"},
	}

	for _, tc := range tests {
		t.Run(tc.input, func(t *testing.T) {
			got := htmlEscape(tc.input)
			if got != tc.expected {
				t.Errorf("htmlEscape(%q) = %q, want %q", tc.input, got, tc.expected)
			}
		})
	}
}

func TestEscapeMarkdown(t *testing.T) {
	got := escapeMarkdown("value | pipe")
	if got != `value \| pipe` {
		t.Errorf("escapeMarkdown = %q, want %q", got, `value \| pipe`)
	}
}
