package hpa

import (
	"io"
	"strings"
)

// WriteHTMLReport writes a single StatusReport as a standalone HTML document
// with inline CSS for portable viewing. The body is assembled by delegating to
// the per-section renderers in report_html_sections.go.
func WriteHTMLReport(w io.Writer, report StatusReport) error {
	a := report.Analysis
	var out strings.Builder

	out.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>HPA Status Report: `)
	out.WriteString(htmlEscape(a.Name))
	out.WriteString("</title>\n<style>\n")
	out.WriteString(htmlCSS())
	out.WriteString("</style>\n</head>\n<body>\n")

	out.WriteString(`<h1>HPA Status Report: `)
	out.WriteString(htmlEscape(a.Name))
	if a.Namespace != "" {
		out.WriteString(" <span class=\"namespace\">(")
		out.WriteString(htmlEscape(a.Namespace))
		out.WriteString(")</span>")
	}
	out.WriteString("</h1>\n")

	writeHTMLOverview(&out, a)
	writeHTMLSummary(&out, a)
	writeHTMLConditions(&out, a)
	writeHTMLMetrics(&out, a)
	writeHTMLRecommendations(&out, a)
	writeHTMLSuggestions(&out, a)
	writeHTMLEvents(&out, report)
	writeHTMLPodAnalysis(&out, a)
	writeHTMLSimulation(&out, a)
	writeHTMLMetricFreshness(&out, a)
	writeHTMLCapacityContext(&out, a)

	out.WriteString("<footer>Generated by kubectl-hpa-status</footer>\n")
	out.WriteString("</body>\n</html>\n")

	_, err := io.WriteString(w, out.String())
	return err
}

// htmlConditionStatus returns a color-coded condition status for HTML.
func htmlConditionStatus(status string) string {
	class := "cond-unknown"
	switch status {
	case "True":
		class = "cond-true"
	case "False":
		class = "cond-false"
	}
	return formatHTMLSpan(class, htmlEscape(status))
}

// htmlFreshnessBadge returns a color-coded freshness status badge for HTML.
func htmlFreshnessBadge(status string) string {
	class := "cond-unknown"
	switch status {
	case string(FreshnessOK):
		class = "cond-true"
	case string(FreshnessMissing):
		class = "cond-false"
	case string(FreshnessStale):
		class = "health-limited"
	}
	return formatHTMLSpan(class, htmlEscape(status))
}

func formatHTMLSpan(class, content string) string {
	return `<span class="` + class + `">` + content + `</span>`
}
