package hpa

import (
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/mattsu2020/kubectl-hpa-status/internal/style"
)

// WriteRetrospectiveTimeline renders a RetrospectiveTimeline as a compact
// text timeline matching the user-facing output format:
//
//	10:01 desired 3 -> 5   cpu 142% over target
//	10:02 scaleUp limited by policy: +2 pods / 60s
func WriteRetrospectiveTimeline(w io.Writer, tl RetrospectiveTimeline, theme style.Theme) error {
	var out strings.Builder

	out.WriteString(fmt.Sprintf("HPA Scaling Timeline: %s (%s)  since %s ago\n\n",
		tl.HPAName, tl.Namespace, formatDuration(time.Since(tl.Since))))

	if len(tl.Warnings) > 0 {
		for _, warn := range tl.Warnings {
			out.WriteString(fmt.Sprintf("Warning: %s\n", warn))
		}
		out.WriteString("\n")
	}

	if len(tl.Entries) == 0 {
		out.WriteString("No scaling events found in the requested time window.\n\n")
	} else {
		for _, entry := range tl.Entries {
			timeStr := entry.Timestamp.Format("15:04:05")
			prefix := categoryPrefix(entry.Category)
			out.WriteString(fmt.Sprintf("%s %s%s\n", timeStr, prefix, entry.Message))
		}
		out.WriteString("\n")
	}

	out.WriteString("Note: " + tl.Disclaimer + "\n")

	_, err := io.WriteString(w, out.String())
	return err
}

// WriteRetrospectiveMarkdown renders a RetrospectiveTimeline as a Markdown document.
func WriteRetrospectiveMarkdown(w io.Writer, tl RetrospectiveTimeline) error {
	var out strings.Builder

	out.WriteString(fmt.Sprintf("# HPA Scaling Timeline: %s/%s\n\n", tl.Namespace, tl.HPAName))
	out.WriteString(fmt.Sprintf("- **Since:** %s\n- **Until:** %s\n- **Entries:** %d\n\n",
		tl.Since.Format(time.RFC3339), tl.Until.Format(time.RFC3339), len(tl.Entries)))

	if len(tl.Warnings) > 0 {
		out.WriteString("## Warnings\n\n")
		for _, warn := range tl.Warnings {
			out.WriteString(fmt.Sprintf("- %s\n", escapeMarkdown(warn)))
		}
		out.WriteString("\n")
	}

	if len(tl.Entries) > 0 {
		out.WriteString("| Time | Category | Message | Source | Confidence |\n")
		out.WriteString("|------|----------|---------|--------|------------|\n")
		for _, entry := range tl.Entries {
			out.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s |\n",
				entry.Timestamp.Format("15:04:05"),
				entry.Category,
				escapeMarkdown(entry.Message),
				entry.Source,
				entry.Confidence))
		}
		out.WriteString("\n")
	}

	out.WriteString(fmt.Sprintf("> %s\n", escapeMarkdown(tl.Disclaimer)))

	_, err := io.WriteString(w, out.String())
	return err
}

// WriteRetrospectiveHTML renders a RetrospectiveTimeline as a standalone HTML page.
func WriteRetrospectiveHTML(w io.Writer, tl RetrospectiveTimeline) error {
	var out strings.Builder

	out.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>HPA Scaling Timeline: `)
	out.WriteString(htmlEscape(tl.HPAName))
	out.WriteString("</title>\n<style>\n")
	out.WriteString(htmlCSS())
	out.WriteString("</style>\n</head>\n<body>\n")

	out.WriteString(fmt.Sprintf("<h1>HPA Scaling Timeline: %s/%s</h1>\n", htmlEscape(tl.Namespace), htmlEscape(tl.HPAName)))
	out.WriteString(fmt.Sprintf("<p>Since: %s | Until: %s | Entries: %d</p>\n",
		tl.Since.Format(time.RFC3339), tl.Until.Format(time.RFC3339), len(tl.Entries)))

	if len(tl.Warnings) > 0 {
		out.WriteString("<h2>Warnings</h2>\n<ul>\n")
		for _, warn := range tl.Warnings {
			out.WriteString(fmt.Sprintf("<li>%s</li>\n", htmlEscape(warn)))
		}
		out.WriteString("</ul>\n")
	}

	if len(tl.Entries) > 0 {
		out.WriteString("<table>\n<tr><th>Time</th><th>Category</th><th>Message</th><th>Source</th><th>Confidence</th></tr>\n")
		for _, entry := range tl.Entries {
			out.WriteString("<tr>")
			out.WriteString(fmt.Sprintf("<td>%s</td>", entry.Timestamp.Format("15:04:05")))
			out.WriteString(fmt.Sprintf("<td>%s</td>", htmlEscape(entry.Category)))
			out.WriteString(fmt.Sprintf("<td>%s</td>", htmlEscape(entry.Message)))
			out.WriteString(fmt.Sprintf("<td>%s</td>", htmlEscape(entry.Source)))
			out.WriteString(fmt.Sprintf("<td>%s</td>", htmlEscape(entry.Confidence)))
			out.WriteString("</tr>\n")
		}
		out.WriteString("</table>\n")
	}

	out.WriteString(fmt.Sprintf("<p class=\"disclaimer\">%s</p>\n", htmlEscape(tl.Disclaimer)))
	out.WriteString("<footer>Generated by kubectl-hpa-status</footer>\n")
	out.WriteString("</body>\n</html>\n")

	_, err := io.WriteString(w, out.String())
	return err
}

// formatDuration returns a human-readable duration string like "30m" or "1h30m".
func formatDuration(d time.Duration) string {
	d = d.Round(time.Minute)
	if d < time.Minute {
		return "0m"
	}
	h := int(d.Hours())
	m := int(d.Minutes()) % 60
	if h > 0 && m > 0 {
		return fmt.Sprintf("%dh%dm", h, m)
	}
	if h > 0 {
		return fmt.Sprintf("%dh", h)
	}
	return fmt.Sprintf("%dm", m)
}
