package render

import (
	"io"
	"strings"

	hpa "github.com/mattsu2020/kubectl-hpa-status/pkg/hpa"
	"github.com/mattsu2020/kubectl-hpa-status/pkg/hpa/rendutil"
)

// WriteHTMLReport writes a single StatusReport as a standalone HTML document
// with inline CSS for portable viewing. The body is assembled by delegating to
// the per-section renderers in report_html_sections.go.
func WriteHTMLReport(w io.Writer, report hpa.StatusReport) error {
	a := report.Analysis
	var out strings.Builder

	out.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>HPA Status Report: `)
	out.WriteString(rendutil.HTMLEscape(a.Name))
	out.WriteString("</title>\n<style>\n")
	out.WriteString(rendutil.HTMLCSS())
	out.WriteString("</style>\n</head>\n<body>\n")
	writeHTMLReportContent(&out, report)
	out.WriteString("<footer>Generated by kubectl-hpa-status</footer>\n")
	out.WriteString("</body>\n</html>\n")

	_, err := io.WriteString(w, out.String())
	return err
}

// WriteHTMLReports writes multiple HPA reports as sections in one valid HTML
// document. Concatenating standalone documents produces invalid markup and
// causes browsers and downstream parsers to ignore later reports.
func WriteHTMLReports(w io.Writer, reports []hpa.StatusReport) error {
	var out strings.Builder
	out.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>HPA Status Reports</title>
<style>
`)
	out.WriteString(rendutil.HTMLCSS())
	out.WriteString("</style>\n</head>\n<body>\n")
	for _, report := range reports {
		out.WriteString("<section class=\"hpa-report\">\n")
		writeHTMLReportContent(&out, report)
		out.WriteString("</section>\n")
	}
	out.WriteString("<footer>Generated by kubectl-hpa-status</footer>\n")
	out.WriteString("</body>\n</html>\n")
	_, err := io.WriteString(w, out.String())
	return err
}

func writeHTMLReportContent(out *strings.Builder, report hpa.StatusReport) {
	a := report.Analysis

	out.WriteString(`<h1>HPA Status Report: `)
	out.WriteString(rendutil.HTMLEscape(a.Name))
	if a.Namespace != "" {
		out.WriteString(" <span class=\"namespace\">(")
		out.WriteString(rendutil.HTMLEscape(a.Namespace))
		out.WriteString(")</span>")
	}
	out.WriteString("</h1>\n")

	writeHTMLOverview(out, a)
	writeHTMLSummary(out, a)
	writeHTMLConditions(out, a)
	writeHTMLMetrics(out, a)
	writeHTMLRecommendations(out, a)
	writeHTMLSuggestions(out, a)
	writeHTMLEvents(out, report)
	writeHTMLPodAnalysis(out, a)
	writeHTMLSimulation(out, a)
	writeHTMLMetricFreshness(out, a)
	writeHTMLCapacityContext(out, a)
}

// htmlConditionStatus returns a color-coded condition status for HTML.
func htmlConditionStatus(status string) string {
	class := "cond-unknown"
	switch status {
	case "True":
		class = "cond-true"
	case "False":
		class = "cond-false"
	}
	return formatHTMLSpan(class, rendutil.HTMLEscape(status))
}

// htmlFreshnessBadge returns a color-coded freshness status badge for HTML.
func htmlFreshnessBadge(status string) string {
	class := "cond-unknown"
	switch status {
	case string(hpa.FreshnessOK):
		class = "cond-true"
	case string(hpa.FreshnessMissing):
		class = "cond-false"
	case string(hpa.FreshnessStale):
		class = "health-limited"
	}
	return formatHTMLSpan(class, rendutil.HTMLEscape(status))
}

func formatHTMLSpan(class, content string) string {
	return `<span class="` + class + `">` + content + `</span>`
}
