package render

import (
	"fmt"
	"io"
	"strings"

	hpa "github.com/mattsu2020/kubectl-hpa-status/pkg/hpa"
	"github.com/mattsu2020/kubectl-hpa-status/pkg/hpa/rendutil"
)

// WriteMarkdownListReport writes a ListReport as a Markdown table.
func WriteMarkdownListReport(w io.Writer, report hpa.ListReport) error {
	var out strings.Builder

	out.WriteString("# HPA List Report\n\n")

	if len(report.Items) == 0 {
		out.WriteString("_No HPAs found._\n")
		_, err := io.WriteString(w, out.String())
		return err
	}

	out.WriteString("| Namespace | Name | Target | Current | Desired | Min | Max | Health | Score | Summary |\n")
	out.WriteString("|-----------|------|--------|---------|---------|-----|-----|--------|-------|--------|\n")

	for _, item := range report.Items {
		out.WriteString("| ")
		out.WriteString(item.Namespace)
		out.WriteString(" | ")
		out.WriteString(item.Name)
		out.WriteString(" | ")
		out.WriteString(item.Target)
		out.WriteString(" | ")
		out.WriteString(fmt.Sprintf("%d", item.Current))
		out.WriteString(" | ")
		out.WriteString(fmt.Sprintf("%d", item.Desired))
		out.WriteString(" | ")
		out.WriteString(fmt.Sprintf("%d", item.Min))
		out.WriteString(" | ")
		out.WriteString(fmt.Sprintf("%d", item.Max))
		out.WriteString(" | ")
		out.WriteString(item.Health)
		out.WriteString(" | ")
		out.WriteString(fmt.Sprintf("%d", item.HealthScore))
		out.WriteString(" | ")
		out.WriteString(rendutil.EscapeMarkdown(item.Summary))
		out.WriteString(" |\n")
	}

	out.WriteString("\n---\nGenerated by kubectl-hpa-status\n")

	_, err := io.WriteString(w, out.String())
	return err
}

// WriteHTMLListReport writes a ListReport as a standalone HTML document.
func WriteHTMLListReport(w io.Writer, report hpa.ListReport) error {
	var out strings.Builder

	out.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>HPA List Report</title>
<style>
`)
	out.WriteString(rendutil.HTMLCSS())
	out.WriteString("</style>\n</head>\n<body>\n")
	out.WriteString("<h1>HPA List Report</h1>\n")

	if len(report.Items) == 0 {
		out.WriteString("<p><em>No HPAs found.</em></p>\n")
	} else {
		out.WriteString("<table>\n<tr><th>Namespace</th><th>Name</th><th>Target</th><th>Current</th><th>Desired</th><th>Min</th><th>Max</th><th>Health</th><th>Score</th><th>Summary</th></tr>\n")
		for _, item := range report.Items {
			out.WriteString("<tr><td>")
			out.WriteString(rendutil.HTMLEscape(item.Namespace))
			out.WriteString("</td><td>")
			out.WriteString(rendutil.HTMLEscape(item.Name))
			out.WriteString("</td><td>")
			out.WriteString(rendutil.HTMLEscape(item.Target))
			out.WriteString("</td><td>")
			out.WriteString(fmt.Sprintf("%d", item.Current))
			out.WriteString("</td><td>")
			out.WriteString(fmt.Sprintf("%d", item.Desired))
			out.WriteString("</td><td>")
			out.WriteString(fmt.Sprintf("%d", item.Min))
			out.WriteString("</td><td>")
			out.WriteString(fmt.Sprintf("%d", item.Max))
			out.WriteString("</td><td>")
			out.WriteString(rendutil.HTMLHealthBadge(item.Health, item.HealthScore))
			out.WriteString("</td><td>")
			out.WriteString(fmt.Sprintf("%d", item.HealthScore))
			out.WriteString("</td><td>")
			out.WriteString(rendutil.HTMLEscape(item.Summary))
			out.WriteString("</td></tr>\n")
		}
		out.WriteString("</table>\n")
	}

	out.WriteString("<footer>Generated by kubectl-hpa-status</footer>\n")
	out.WriteString("</body>\n</html>\n")

	_, err := io.WriteString(w, out.String())
	return err
}
