// Package render holds the Markdown/HTML report renderers extracted from
// pkg/hpa. The renderers consume the pkg/hpa analysis model (Analysis,
// StatusReport, ListReport) and the shared escape/format helpers in
// pkg/hpa/rendutil. pkg/hpa retains the data model and analysis logic; this
// package is the pure presentation layer.
package render

import (
	"fmt"
	"io"
	"strings"

	hpa "github.com/mattsu2020/kubectl-hpa-status/pkg/hpa"
	"github.com/mattsu2020/kubectl-hpa-status/pkg/hpa/rendutil"
)

// WriteMarkdownReport writes a single StatusReport as a Markdown document.
// The output is suitable for Slack, Notion, or incident reports.
func WriteMarkdownReport(w io.Writer, report hpa.StatusReport) error {
	var out strings.Builder
	// Pass Analysis by pointer: 11 append* helpers each previously copied the
	// 63-field Analysis struct.
	a := &report.Analysis
	appendMarkdownHeader(&out, a)
	appendMarkdownSummary(&out, a)
	appendMarkdownConditions(&out, a)
	appendMarkdownMetrics(&out, a)
	appendMarkdownActions(&out, a)
	appendMarkdownSuggestions(&out, a)
	appendMarkdownEvents(&out, report)
	appendMarkdownPodAnalysis(&out, a)
	appendMarkdownSimulation(&out, a)
	appendMarkdownMetricFreshness(&out, a)
	appendMarkdownCapacityContext(&out, a)
	appendMarkdownStructuredDecisionTrace(&out, a)
	out.WriteString("---\nGenerated by kubectl-hpa-status\n")

	_, err := io.WriteString(w, out.String())
	return err
}

func appendMarkdownHeader(out *strings.Builder, a *hpa.Analysis) {
	out.WriteString("# HPA Status Report: ")
	out.WriteString(a.Name)
	if a.Namespace != "" {
		out.WriteString(" (")
		out.WriteString(a.Namespace)
		out.WriteString(")")
	}
	out.WriteString("\n\n")

	out.WriteString("**Target:** ")
	out.WriteString(a.Target)
	out.WriteString("\n")

	out.WriteString("**Health:** ")
	out.WriteString(a.Health)
	if a.HealthScore > 0 {
		out.WriteString(fmt.Sprintf(" (%d/100)", a.HealthScore))
	}
	out.WriteString("\n")

	out.WriteString(fmt.Sprintf("**Replicas:** current=%d desired=%d min=%d max=%d\n", a.Current, a.Desired, a.Min, a.Max))
	out.WriteString("\n")
}

func appendMarkdownSummary(out *strings.Builder, a *hpa.Analysis) {
	out.WriteString("## Summary\n\n")
	if a.Summary != "" {
		out.WriteString(a.Summary)
		out.WriteString("\n")
	} else {
		out.WriteString("_No summary available._\n")
	}
	out.WriteString("\n")
}

func appendMarkdownConditions(out *strings.Builder, a *hpa.Analysis) {
	// Conditions table
	out.WriteString("## Conditions\n\n")
	if len(a.Conditions) == 0 {
		out.WriteString("_No conditions reported._\n")
	} else {
		out.WriteString("| Type | Status | Reason | Message |\n")
		out.WriteString("|------|--------|--------|--------|\n")
		for _, c := range a.Conditions {
			out.WriteString("| ")
			out.WriteString(c.Type)
			out.WriteString(" | ")
			out.WriteString(c.Status)
			out.WriteString(" | ")
			out.WriteString(c.Reason)
			out.WriteString(" | ")
			out.WriteString(rendutil.EscapeMarkdown(c.Message))
			out.WriteString(" |\n")
		}
	}
	out.WriteString("\n")
}

func appendMarkdownMetrics(out *strings.Builder, a *hpa.Analysis) {
	// Metrics table
	out.WriteString("## Metrics\n\n")
	if len(a.Metrics) == 0 {
		out.WriteString("_No current metrics reported._\n")
	} else {
		out.WriteString("| Metric | Current | Target | Ratio |\n")
		out.WriteString("|--------|---------|--------|-------|\n")
		for _, m := range a.Metrics {
			name := m.Name
			if name == "" {
				name = m.Type
			}
			ratio := ""
			if m.Ratio != nil {
				ratio = fmt.Sprintf("%.3f", *m.Ratio)
			}
			out.WriteString("| ")
			out.WriteString(name)
			out.WriteString(" | ")
			out.WriteString(m.Current)
			out.WriteString(" | ")
			out.WriteString(m.Target)
			out.WriteString(" | ")
			out.WriteString(ratio)
			out.WriteString(" |\n")
		}
	}
	out.WriteString("\n")
}

func appendMarkdownActions(out *strings.Builder, a *hpa.Analysis) {
	// Recommendations
	if len(a.Actions) == 0 {
		return
	}
	out.WriteString("## Recommendations\n\n")
	for _, action := range a.Actions {
		out.WriteString("- ")
		out.WriteString(action)
		out.WriteString("\n")
	}
	out.WriteString("\n")
}

func appendMarkdownSuggestions(out *strings.Builder, a *hpa.Analysis) {
	// Suggestions
	if len(a.Suggestions) == 0 {
		return
	}
	out.WriteString("## Suggestions\n\n")
	for _, s := range a.Suggestions {
		out.WriteString("- **")
		out.WriteString(s.Title)
		out.WriteString("**: ")
		out.WriteString(s.Description)
		out.WriteString("\n")
		if s.Command != "" {
			out.WriteString("  ```\n  ")
			out.WriteString(s.Command)
			out.WriteString("\n  ```\n")
		}
		if s.Risk != "" {
			out.WriteString("  - Risk: ")
			out.WriteString(s.Risk)
			out.WriteString("\n")
		}
	}
	out.WriteString("\n")
}

func appendMarkdownEvents(out *strings.Builder, report hpa.StatusReport) {
	// Events
	if len(report.Events) == 0 {
		return
	}
	out.WriteString("## Events\n\n")
	out.WriteString("| Reason | Message |\n")
	out.WriteString("|--------|--------|\n")
	for _, e := range report.Events {
		out.WriteString("| ")
		out.WriteString(e.Reason)
		out.WriteString(" | ")
		out.WriteString(rendutil.EscapeMarkdown(e.Message))
		out.WriteString(" |\n")
	}
	out.WriteString("\n")
}

func appendMarkdownPodAnalysis(out *strings.Builder, a *hpa.Analysis) {
	// Pod Analysis
	if a.PodAnalysis == nil {
		return
	}
	pa := a.PodAnalysis
	out.WriteString("## Pod Analysis\n\n")
	out.WriteString(fmt.Sprintf("- **Total:** %d  **Ready:** %d  **Unready:** %d  **Pending:** %d  **Terminating:** %d\n", pa.Total, pa.Ready, pa.Unready, pa.Pending, pa.Terminating))
	if len(pa.ResourceIssues) > 0 {
		out.WriteString("\n### Missing Resources\n\n")
		out.WriteString("| Pod | Container | Resource | Category |\n")
		out.WriteString("|-----|-----------|----------|----------|\n")
		for _, issue := range pa.ResourceIssues {
			out.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n", rendutil.EscapeMarkdown(issue.Pod), rendutil.EscapeMarkdown(issue.Container), rendutil.EscapeMarkdown(issue.Resource), rendutil.EscapeMarkdown(issue.Category)))
		}
		out.WriteString("\n")
	}
	if len(pa.ContainerChecks) > 0 {
		out.WriteString("\n### Container Checks\n\n")
		out.WriteString("| Container | Found | Message |\n")
		out.WriteString("|-----------|-------|--------|\n")
		for _, check := range pa.ContainerChecks {
			msg := check.Message
			if msg == "" {
				msg = "OK"
			}
			out.WriteString(fmt.Sprintf("| %s | %v | %s |\n", rendutil.EscapeMarkdown(check.Container), check.Found, rendutil.EscapeMarkdown(msg)))
		}
		out.WriteString("\n")
	}
}

func appendMarkdownSimulation(out *strings.Builder, a *hpa.Analysis) {
	// Simulation
	if a.Simulation == nil {
		return
	}
	sim := a.Simulation
	out.WriteString("## Simulation\n\n")
	out.WriteString(fmt.Sprintf("- **Parameter:** %s\n", sim.Parameter))
	out.WriteString(fmt.Sprintf("- **Original:** %s  **Simulated:** %s\n", sim.OriginalValue, sim.SimulatedValue))
	out.WriteString(fmt.Sprintf("- **Before:** desired=%d health=%s(%d)  **After:** desired=%d health=%s(%d)\n",
		sim.Before.DesiredReplicas, sim.Before.Health, sim.Before.HealthScore,
		sim.After.DesiredReplicas, sim.After.Health, sim.After.HealthScore))
	if sim.RiskAssessment != "" {
		out.WriteString(fmt.Sprintf("- **Risk:** %s\n", sim.RiskAssessment))
	}
	if len(sim.Interpretation) > 0 {
		out.WriteString("\n")
		for _, line := range sim.Interpretation {
			out.WriteString(fmt.Sprintf("- %s\n", line))
		}
	}
	out.WriteString("\n")
}

func appendMarkdownMetricFreshness(out *strings.Builder, a *hpa.Analysis) {
	// Metrics Freshness
	if len(a.MetricFreshnessEntries) == 0 {
		return
	}
	out.WriteString("## Metrics Freshness\n\n")
	for _, mf := range a.MetricFreshnessEntries {
		out.WriteString(fmt.Sprintf("### %s (%s) — %s\n\n", mf.Name, mf.Type, mf.Status))
		if mf.Source != "" {
			out.WriteString(fmt.Sprintf("- **Source:** %s\n", mf.Source))
		}
		if mf.Window != "" {
			out.WriteString(fmt.Sprintf("- **Window:** %s\n", mf.Window))
		}
		if mf.Risk != "" {
			out.WriteString(fmt.Sprintf("- **Risk:** %s\n", mf.Risk))
		}
		if len(mf.Evidence) > 0 {
			out.WriteString("- **Evidence:**\n")
			for _, e := range mf.Evidence {
				out.WriteString(fmt.Sprintf("  - %s\n", e))
			}
		}
		if len(mf.NextSteps) > 0 {
			out.WriteString("- **Next Steps:**\n")
			for _, ns := range mf.NextSteps {
				out.WriteString(fmt.Sprintf("  - `%s`\n", ns))
			}
		}
		out.WriteString("\n")
	}
}

func appendMarkdownCapacityContext(out *strings.Builder, a *hpa.Analysis) {
	// Capacity Context
	if a.CapacityContext == nil {
		return
	}
	cc := a.CapacityContext
	if len(cc.PendingPods) == 0 && len(cc.QuotaConstraints) == 0 && len(cc.PDBInterference) == 0 && len(cc.NodeHints) == 0 {
		return
	}
	out.WriteString("## Capacity Context\n\n")
	if len(cc.PendingPods) > 0 {
		out.WriteString("### Pending Pods\n\n")
		out.WriteString("| Name | Unschedulable | Reasons |\n")
		out.WriteString("|------|---------------|--------|\n")
		for _, p := range cc.PendingPods {
			reasons := strings.Join(p.Reasons, "; ")
			out.WriteString(fmt.Sprintf("| %s | %v | %s |\n", rendutil.EscapeMarkdown(p.Name), p.Unschedulable, rendutil.EscapeMarkdown(reasons)))
		}
		out.WriteString("\n")
	}
	if len(cc.QuotaConstraints) > 0 {
		out.WriteString("### ResourceQuotas\n\n")
		out.WriteString("| Name | Resource | Used | Hard | Message |\n")
		out.WriteString("|------|----------|------|------|--------|\n")
		for _, q := range cc.QuotaConstraints {
			out.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s |\n", rendutil.EscapeMarkdown(q.Name), rendutil.EscapeMarkdown(q.Resource), rendutil.EscapeMarkdown(q.Used), rendutil.EscapeMarkdown(q.Hard), rendutil.EscapeMarkdown(q.Message)))
		}
		out.WriteString("\n")
	}
	if len(cc.PDBInterference) > 0 {
		out.WriteString("### PodDisruptionBudgets\n\n")
		out.WriteString("| Name | Disruption |\n")
		out.WriteString("|------|-----------|\n")
		for _, p := range cc.PDBInterference {
			out.WriteString(fmt.Sprintf("| %s | %s |\n", rendutil.EscapeMarkdown(p.Name), rendutil.EscapeMarkdown(p.Disruption)))
		}
		out.WriteString("\n")
	}
	if len(cc.NodeHints) > 0 {
		out.WriteString("### Hints\n\n")
		for _, hint := range cc.NodeHints {
			out.WriteString(fmt.Sprintf("- %s\n", hint))
		}
		out.WriteString("\n")
	}
}

func appendMarkdownStructuredDecisionTrace(out *strings.Builder, a *hpa.Analysis) {
	// Structured Decision Trace
	if a.StructuredDecisionTrace == nil {
		return
	}
	sdt := a.StructuredDecisionTrace
	out.WriteString("## Structured Decision Trace\n\n")
	out.WriteString(fmt.Sprintf("- **Schema:** %s\n", sdt.SchemaVersion))
	out.WriteString(fmt.Sprintf("- **HPA:** %s/%s\n", sdt.Namespace, sdt.Name))
	out.WriteString(fmt.Sprintf("- **Replicas:** current=%d desired=%d min=%d max=%d\n",
		sdt.CurrentReplicas, sdt.VisibleDesiredReplicas, sdt.MinReplicas, sdt.MaxReplicas))
	if sdt.EstimatedRawDesired > 0 {
		out.WriteString(fmt.Sprintf("- **Estimated raw desired:** %d\n", sdt.EstimatedRawDesired))
	}
	if sdt.WinnerMetric != "" {
		out.WriteString(fmt.Sprintf("- **Winner metric:** %s (confidence: %s)\n", sdt.WinnerMetric, string(sdt.WinnerConfidence)))
	}
	if sdt.LimitClamp != "" {
		out.WriteString(fmt.Sprintf("- **Limit clamp:** %s\n", sdt.LimitClamp))
	}
	if sdt.Summary != "" {
		out.WriteString(fmt.Sprintf("- **Summary:** %s\n", sdt.Summary))
	}
	if len(sdt.Metrics) > 0 {
		out.WriteString("\n### Metric Analysis\n\n")
		out.WriteString("| Metric | Type | Current | Target | Ratio | Direction | Within Tolerance |\n")
		out.WriteString("|--------|------|---------|--------|-------|-----------|------------------|\n")
		for _, m := range sdt.Metrics {
			ratio := ""
			if m.Ratio != nil {
				ratio = fmt.Sprintf("%.3f", *m.Ratio)
			}
			tolerance := "no"
			if m.WithinTolerance {
				tolerance = "yes"
			}
			out.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s | %s | %s |\n",
				m.Name, m.Type, m.Current, m.Target, ratio, m.DesiredDirection, tolerance))
		}
		out.WriteString("\n")
	}
	if len(sdt.DecisionPath) > 0 {
		out.WriteString("### Decision Path\n\n")
		out.WriteString("| Step | Description | Result | Impact | Confidence |\n")
		out.WriteString("|------|-------------|--------|--------|------------|\n")
		for _, step := range sdt.DecisionPath {
			out.WriteString(fmt.Sprintf("| %d | %s | %s | %s | %s |\n",
				step.Step, step.Description, rendutil.EscapeMarkdown(step.Result), step.Impact, string(step.Confidence)))
		}
		out.WriteString("\n")
	}
}
