package cmd

import (
	"encoding/json"
	"fmt"
	"io"
	"strings"
	"time"

	hpaanalysis "github.com/mattsu2020/kubectl-hpa-status/pkg/hpa"
)

// writeBundleMarkdown renders all bundle sections to an io.Writer.
// Errors from write operations are not propagated; this is best-effort
// rendering consistent with the snapshot command's pattern.
func writeBundleMarkdown(w io.Writer, data *bundleData) {
	_, _ = fmt.Fprintf(w, "# HPA Investigation Bundle: %s/%s\n\n", data.Namespace, data.HPAName)
	_, _ = fmt.Fprintf(w, "**Generated:** %s  \n", data.Timestamp.Format(time.RFC3339))
	_, _ = fmt.Fprintf(w, "**Plugin:** kubectl-hpa-status bundle\n\n")
	_, _ = fmt.Fprint(w, "---\n\n")

	writeBundleTOC(w)
	_, _ = fmt.Fprint(w, "---\n\n")

	writeBundleStatusSummary(w, data)
	writeBundleHPAYAML(w, data)
	writeBundleScaleTarget(w, data)
	writeBundlePodStatusTable(w, data)
	writeBundleContainerStatusTable(w, data)
	writeBundleResourceRequests(w, data)
	writeBundleEventsSection(w, data)
	writeBundleMetricsAPI(w, data)
	writeBundleMetricsDiagnostics(w, data)
	writeBundleCapacityContextSection(w, data)
	writeBundleScalePathSection(w, data)
	writeBundleBlockerSection(w, data)
	writeBundleKEDASection(w, data)
	writeBundleQuotasSection(w, data)
	writeBundleLimitRangesSection(w, data)
	writeBundlePDBsSection(w, data)
	writeBundleNodeCapacitySection(w, data)
	writeBundleRecommendations(w, data)
	writeBundleFullAnalysis(w, data)

	_, _ = fmt.Fprint(w, "---\n_Generated by kubectl-hpa-status bundle_\n")
}

func writeBundleTOC(w io.Writer) {
	_, _ = fmt.Fprint(w, "## Table of Contents\n\n")
	sections := []string{
		"HPA Status Summary",
		"HPA Resource (YAML)",
		"Scale Target Resource",
		"Pod Status",
		"Container Status",
		"Resource Requests/Limits",
		"Events",
		"Metrics API Status",
		"Metrics Diagnostics",
		"Capacity Context",
		"Scale Path",
		"Blocker Analysis",
		"KEDA Status",
		"ResourceQuotas",
		"LimitRanges",
		"PodDisruptionBudgets",
		"Node Capacity",
		"Recommendations",
		"Full Analysis Report",
	}
	for i, s := range sections {
		anchor := strings.ToLower(strings.ReplaceAll(s, " ", "-"))
		anchor = strings.ReplaceAll(anchor, "(", "")
		anchor = strings.ReplaceAll(anchor, ")", "")
		anchor = strings.ReplaceAll(anchor, "/", "")
		_, _ = fmt.Fprintf(w, "%d. [%s](#%s)\n", i+1, s, anchor)
	}
	_, _ = fmt.Fprintln(w)
}

func writeBundleStatusSummary(w io.Writer, data *bundleData) {
	_, _ = fmt.Fprint(w, "## HPA Status Summary\n\n")
	if err := hpaanalysis.WriteMarkdownReport(w, data.StatusReport); err != nil {
		_, _ = fmt.Fprintf(w, "_Error rendering status summary: %v_\n", err)
	}
	_, _ = fmt.Fprint(w, "\n---\n\n")
}

func writeBundleHPAYAML(w io.Writer, data *bundleData) {
	_, _ = fmt.Fprint(w, "## HPA Resource (YAML)\n\n")
	_, _ = fmt.Fprint(w, "```yaml\n")
	_, _ = w.Write(data.HPA)
	_, _ = fmt.Fprint(w, "```\n\n---\n\n")
}

func writeBundleScaleTarget(w io.Writer, data *bundleData) {
	_, _ = fmt.Fprint(w, "## Scale Target Resource\n\n")
	_, _ = fmt.Fprint(w, "```yaml\n")
	_, _ = w.Write(data.ScaleTarget)
	_, _ = fmt.Fprint(w, "```\n\n---\n\n")
}

func writeBundlePodStatusTable(w io.Writer, data *bundleData) {
	_, _ = fmt.Fprint(w, "## Pod Status\n\n")
	if len(data.PodInfos) == 0 {
		_, _ = fmt.Fprint(w, "_No pod information available._\n\n---\n\n")
		return
	}

	_, _ = fmt.Fprint(w, "| Name | Phase | Ready | Unschedulable | Reasons | Node |\n")
	_, _ = fmt.Fprint(w, "|------|-------|-------|---------------|---------|------|\n")
	for _, pod := range data.PodInfos {
		ready := "✓"
		if !pod.Ready {
			ready = "✗"
		}
		unschedulable := "-"
		if pod.Unschedulable {
			unschedulable = "Yes"
		}
		reasons := "-"
		if len(pod.Reasons) > 0 {
			reasons = mdEscape(strings.Join(pod.Reasons, ", "))
		}
		node := pod.NodeName
		if node == "" {
			node = "-"
		}
		_, _ = fmt.Fprintf(w, "| %s | %s | %s | %s | %s | %s |\n",
			mdEscape(pod.Name), mdEscape(pod.Phase), ready, unschedulable, reasons, mdEscape(node))
	}
	_, _ = fmt.Fprint(w, "\n---\n\n")
}

func writeBundleContainerStatusTable(w io.Writer, data *bundleData) {
	_, _ = fmt.Fprint(w, "## Container Status\n\n")
	if len(data.ContainerStatuses) == 0 {
		_, _ = fmt.Fprint(w, "_No container status data available._\n\n---\n\n")
		return
	}

	_, _ = fmt.Fprint(w, "| Pod | Container | Waiting | Waiting Reason | Restarts |\n")
	_, _ = fmt.Fprint(w, "|-----|-----------|---------|----------------|----------|\n")
	for _, cs := range data.ContainerStatuses {
		waiting := "No"
		if cs.Waiting {
			waiting = "Yes"
		}
		waitReason := "-"
		if cs.WaitingReason != "" {
			waitReason = mdEscape(cs.WaitingReason)
		}
		_, _ = fmt.Fprintf(w, "| %s | %s | %s | %s | %d |\n",
			mdEscape(cs.Pod), mdEscape(cs.Container), waiting, waitReason, cs.RestartCount)
	}
	_, _ = fmt.Fprint(w, "\n---\n\n")
}

func writeBundleResourceRequests(w io.Writer, data *bundleData) {
	_, _ = fmt.Fprint(w, "## Resource Requests/Limits\n\n")
	rc := data.StatusReport.Analysis.ResourceCheck
	if rc == nil || len(rc.Warnings) == 0 {
		_, _ = fmt.Fprint(w, "_No resource consistency issues detected._\n\n---\n\n")
		return
	}

	_, _ = fmt.Fprint(w, "| Container | Resource | Category | Severity | Details |\n")
	_, _ = fmt.Fprint(w, "|-----------|----------|----------|----------|--------|\n")
	for _, warn := range rc.Warnings {
		_, _ = fmt.Fprintf(w, "| %s | %s | %s | %s | %s |\n",
			mdEscape(warn.Container), mdEscape(warn.Resource),
			mdEscape(warn.Category), mdEscape(warn.Severity), mdEscape(warn.Details))
	}
	_, _ = fmt.Fprint(w, "\n---\n\n")
}

func writeBundleEventsSection(w io.Writer, data *bundleData) {
	_, _ = fmt.Fprint(w, "## Events\n\n")
	if len(data.Events) == 0 {
		_, _ = fmt.Fprint(w, "_No events collected._\n\n---\n\n")
		return
	}
	_, _ = w.Write(data.Events)
	_, _ = fmt.Fprint(w, "\n---\n\n")
}

func writeBundleMetricsAPI(w io.Writer, data *bundleData) {
	_, _ = fmt.Fprint(w, "## Metrics API Status\n\n")
	_, _ = w.Write(data.MetricsAPI)
	_, _ = fmt.Fprint(w, "\n\n---\n\n")
}

func writeBundleMetricsDiagnostics(w io.Writer, data *bundleData) {
	_, _ = fmt.Fprint(w, "## Metrics Diagnostics\n\n")
	a := data.StatusReport.Analysis

	hasContent := false
	if a.MetricsDiagnostics != nil {
		writeBundleMetricsDiagnosticsSection(w, a.MetricsDiagnostics)
		hasContent = true
	}
	if len(a.MetricFreshnessEntries) > 0 {
		writeBundleMetricFreshness(w, a.MetricFreshnessEntries)
		hasContent = true
	}
	if a.MetricContract != nil {
		writeBundleMetricContract(w, a.MetricContract)
		hasContent = true
	}

	if !hasContent {
		_, _ = fmt.Fprint(w, "_No metrics diagnostics available._\n")
	}

	_, _ = fmt.Fprint(w, "\n---\n\n")
}

func writeBundleMetricsDiagnosticsSection(w io.Writer, md *hpaanalysis.MetricsPipelineDiagnostics) {
	_, _ = fmt.Fprintf(w, "**Overall Status:** %s\n\n", mdEscape(md.OverallStatus))

	if len(md.PerMetricChecks) > 0 {
		_, _ = fmt.Fprint(w, "| Metric Type | Metric Name | Status | Details |\n")
		_, _ = fmt.Fprint(w, "|-------------|-------------|--------|--------|\n")
		for _, check := range md.PerMetricChecks {
			_, _ = fmt.Fprintf(w, "| %s | %s | %s | %s |\n",
				mdEscape(check.MetricType), mdEscape(check.MetricName),
				mdEscape(check.Status), mdEscape(check.Details))
		}
		_, _ = fmt.Fprintln(w)
	}

	if len(md.RemediationSteps) > 0 {
		_, _ = fmt.Fprint(w, "**Remediation Steps:**\n")
		for _, step := range md.RemediationSteps {
			_, _ = fmt.Fprintf(w, "- %s\n", mdEscape(step))
		}
		_, _ = fmt.Fprintln(w)
	}
}

func writeBundleMetricFreshness(w io.Writer, entries []hpaanalysis.MetricFreshness) {
	_, _ = fmt.Fprint(w, "### Metric Freshness\n\n")
	_, _ = fmt.Fprint(w, "| Metric | Type | Status | Age | Source |\n")
	_, _ = fmt.Fprint(w, "|--------|------|--------|-----|--------|\n")
	for _, entry := range entries {
		age := "-"
		if entry.Age > 0 {
			age = entry.Age.String()
		}
		source := "-"
		if entry.Source != "" {
			source = mdEscape(entry.Source)
		}
		_, _ = fmt.Fprintf(w, "| %s | %s | %s | %s | %s |\n",
			mdEscape(entry.Name), mdEscape(entry.Type),
			mdEscape(entry.Status), age, source)
	}
	_, _ = fmt.Fprintln(w)
}

func writeBundleMetricContract(w io.Writer, contract *hpaanalysis.MetricContractReport) {
	_, _ = fmt.Fprint(w, "### Metric Contract\n\n")
	_, _ = fmt.Fprintf(w, "**Status:** %s\n\n", mdEscape(contract.OverallStatus))
	if len(contract.Checks) == 0 {
		return
	}
	_, _ = fmt.Fprint(w, "| Metric Type | Metric Name | API Service | Available | Data Available | Status |\n")
	_, _ = fmt.Fprint(w, "|-------------|-------------|-------------|-----------|----------------|--------|\n")
	for _, check := range contract.Checks {
		apiAvail := "No"
		if check.APIServiceAvailable {
			apiAvail = "Yes"
		}
		dataAvail := "No"
		if check.DataAvailable {
			dataAvail = "Yes"
		}
		_, _ = fmt.Fprintf(w, "| %s | %s | %s | %s | %s | %s |\n",
			mdEscape(check.MetricType), mdEscape(check.MetricName),
			mdEscape(check.APIService), apiAvail, dataAvail, mdEscape(check.Status))
	}
	_, _ = fmt.Fprintln(w)
}

func writeBundleCapacityContextSection(w io.Writer, data *bundleData) {
	_, _ = fmt.Fprint(w, "## Capacity Context\n\n")
	cc := data.StatusReport.Analysis.CapacityContext
	if cc == nil {
		_, _ = fmt.Fprint(w, "_No capacity context available._\n\n---\n\n")
		return
	}

	if len(cc.PendingPods) > 0 {
		_, _ = fmt.Fprint(w, "### Pending Pods\n\n")
		_, _ = fmt.Fprint(w, "| Name | Unschedulable | Reasons |\n")
		_, _ = fmt.Fprint(w, "|------|--------------|---------|\n")
		for _, pod := range cc.PendingPods {
			unsched := "No"
			if pod.Unschedulable {
				unsched = "Yes"
			}
			reasons := "-"
			if len(pod.Reasons) > 0 {
				reasons = mdEscape(strings.Join(pod.Reasons, ", "))
			}
			_, _ = fmt.Fprintf(w, "| %s | %s | %s |\n", mdEscape(pod.Name), unsched, reasons)
		}
		_, _ = fmt.Fprintln(w)
	}

	if len(cc.QuotaConstraints) > 0 {
		_, _ = fmt.Fprint(w, "### Quota Constraints\n\n")
		_, _ = fmt.Fprint(w, "| Name | Resource | Used | Hard | Message |\n")
		_, _ = fmt.Fprint(w, "|------|----------|------|------|---------|\n")
		for _, q := range cc.QuotaConstraints {
			_, _ = fmt.Fprintf(w, "| %s | %s | %s | %s | %s |\n",
				mdEscape(q.Name), mdEscape(q.Resource),
				mdEscape(q.Used), mdEscape(q.Hard), mdEscape(q.Message))
		}
		_, _ = fmt.Fprintln(w)
	}

	if len(cc.PDBInterference) > 0 {
		_, _ = fmt.Fprint(w, "### PDB Interference\n\n")
		_, _ = fmt.Fprint(w, "| Name | Min Available | Max Unavailable | Disruption |\n")
		_, _ = fmt.Fprint(w, "|------|--------------|----------------|------------|\n")
		for _, pdb := range cc.PDBInterference {
			_, _ = fmt.Fprintf(w, "| %s | %s | %s | %s |\n",
				mdEscape(pdb.Name), mdEscape(pdb.MinAvailable),
				mdEscape(pdb.MaxUnavailable), mdEscape(pdb.Disruption))
		}
		_, _ = fmt.Fprintln(w)
	}

	if len(cc.NodeHints) > 0 {
		_, _ = fmt.Fprint(w, "### Node Hints\n\n")
		for _, hint := range cc.NodeHints {
			_, _ = fmt.Fprintf(w, "- %s\n", mdEscape(hint))
		}
		_, _ = fmt.Fprintln(w)
	}

	_, _ = fmt.Fprint(w, "\n---\n\n")
}

func writeBundleScalePathSection(w io.Writer, data *bundleData) {
	_, _ = fmt.Fprint(w, "## Scale Path\n\n")
	sp := data.StatusReport.Analysis.ScalePath
	if sp == nil {
		_, _ = fmt.Fprint(w, "_No scale path analysis available._\n\n---\n\n")
		return
	}

	if len(sp.Steps) > 0 {
		_, _ = fmt.Fprint(w, "| Step | Name | Summary |\n")
		_, _ = fmt.Fprint(w, "|------|------|--------|\n")
		for i, step := range sp.Steps {
			_, _ = fmt.Fprintf(w, "| %d | %s | %s |\n",
				i+1, mdEscape(step.Name), mdEscape(step.Summary))
		}
		_, _ = fmt.Fprintln(w)
	}

	if sp.BlockingPoint != "" {
		_, _ = fmt.Fprintf(w, "**Blocking Point:** %s\n\n", mdEscape(sp.BlockingPoint))
	}

	if len(sp.Evidence) > 0 {
		_, _ = fmt.Fprint(w, "**Evidence:**\n")
		for _, e := range sp.Evidence {
			_, _ = fmt.Fprintf(w, "- %s\n", mdEscape(e))
		}
		_, _ = fmt.Fprintln(w)
	}

	if len(sp.NextActions) > 0 {
		_, _ = fmt.Fprint(w, "**Next Actions:**\n")
		for _, a := range sp.NextActions {
			_, _ = fmt.Fprintf(w, "- %s\n", mdEscape(a))
		}
		_, _ = fmt.Fprintln(w)
	}

	_, _ = fmt.Fprint(w, "\n---\n\n")
}

func writeBundleBlockerSection(w io.Writer, data *bundleData) {
	_, _ = fmt.Fprint(w, "## Blocker Analysis\n\n")
	br := data.StatusReport.Analysis.BlockerReport
	if br == nil {
		_, _ = fmt.Fprint(w, "_No blocker analysis available._\n\n---\n\n")
		return
	}

	_, _ = fmt.Fprintf(w, "**Summary:** %s\n\n", mdEscape(br.Summary))
	_, _ = fmt.Fprintf(w, "**HPA Wants Scale:** %v | **Desired:** %d | **Ready:** %d\n\n",
		br.HPAWantsScale, br.DesiredReplicas, br.ReadyReplicas)

	if len(br.Blockers) > 0 {
		_, _ = fmt.Fprint(w, "| Severity | Category | Message | Detail |\n")
		_, _ = fmt.Fprint(w, "|----------|----------|---------|--------|\n")
		for _, b := range br.Blockers {
			_, _ = fmt.Fprintf(w, "| %s | %s | %s | %s |\n",
				mdEscape(string(b.Severity)), mdEscape(b.Category),
				mdEscape(b.Message), mdEscape(b.Detail))
		}
		_, _ = fmt.Fprintln(w)
	}

	if br.Interpretation != "" {
		_, _ = fmt.Fprintf(w, "**Interpretation:** %s\n\n", mdEscape(br.Interpretation))
	}

	if len(br.NextCommands) > 0 {
		_, _ = fmt.Fprint(w, "**Investigation Commands:**\n")
		for _, cmd := range br.NextCommands {
			_, _ = fmt.Fprintf(w, "```bash\n%s\n```\n", cmd)
		}
		_, _ = fmt.Fprintln(w)
	}

	_, _ = fmt.Fprint(w, "\n---\n\n")
}

func writeBundleKEDASection(w io.Writer, data *bundleData) {
	ki := data.StatusReport.Analysis.KEDAInfo
	if ki == nil {
		return // Omit entire section when KEDA is not detected.
	}

	_, _ = fmt.Fprint(w, "## KEDA Status\n\n")
	_, _ = fmt.Fprintf(w, "**ScaledObject:** %s\n\n", mdEscape(ki.ScaledObjectName))

	if ki.PollingInterval != nil {
		_, _ = fmt.Fprintf(w, "**Polling Interval:** %ds\n", *ki.PollingInterval)
	}
	if ki.CooldownPeriod != nil {
		_, _ = fmt.Fprintf(w, "**Cooldown Period:** %ds\n", *ki.CooldownPeriod)
	}
	if ki.MinReplicaCount != nil {
		_, _ = fmt.Fprintf(w, "**Min Replica Count:** %d\n", *ki.MinReplicaCount)
	}
	if ki.MaxReplicaCount != nil {
		_, _ = fmt.Fprintf(w, "**Max Replica Count:** %d\n", *ki.MaxReplicaCount)
	}

	if len(ki.Triggers) > 0 {
		_, _ = fmt.Fprint(w, "\n### Triggers\n\n")
		_, _ = fmt.Fprint(w, "| Type | Name | Status | Threshold | Current | Auth Ref |\n")
		_, _ = fmt.Fprint(w, "|------|------|--------|-----------|---------|----------|\n")
		for _, t := range ki.Triggers {
			authRef := "-"
			if t.AuthRef != "" {
				authRef = mdEscape(t.AuthRef)
			}
			_, _ = fmt.Fprintf(w, "| %s | %s | %s | %s | %s | %s |\n",
				mdEscape(t.Type), mdEscape(t.Name), mdEscape(t.Status),
				mdEscape(t.Threshold), mdEscape(t.CurrentValue), authRef)
		}
		_, _ = fmt.Fprintln(w)
	}

	if ki.Fallback != nil {
		_, _ = fmt.Fprintf(w, "**Fallback:** failureThreshold=%d, replicas=%d\n\n",
			ki.Fallback.FailureThreshold, ki.Fallback.Replicas)
	}

	if len(ki.Lines) > 0 {
		_, _ = fmt.Fprint(w, "**Notes:**\n")
		for _, line := range ki.Lines {
			_, _ = fmt.Fprintf(w, "- %s\n", mdEscape(line))
		}
		_, _ = fmt.Fprintln(w)
	}

	_, _ = fmt.Fprint(w, "\n---\n\n")
}

func writeBundleQuotasSection(w io.Writer, data *bundleData) {
	_, _ = fmt.Fprint(w, "## ResourceQuotas\n\n")
	if len(data.ResourceQuotas) == 0 {
		_, _ = fmt.Fprint(w, "_No ResourceQuotas found in namespace._\n\n---\n\n")
		return
	}

	_, _ = fmt.Fprint(w, "| Name | Resource | Used | Hard | Ratio |\n")
	_, _ = fmt.Fprint(w, "|------|----------|------|------|-------|\n")
	for _, q := range data.ResourceQuotas {
		_, _ = fmt.Fprintf(w, "| %s | %s | %s | %s | %.0f%% |\n",
			mdEscape(q.Name), mdEscape(q.Resource),
			mdEscape(q.Used), mdEscape(q.Hard), q.Ratio*100)
	}
	_, _ = fmt.Fprint(w, "\n---\n\n")
}

func writeBundleLimitRangesSection(w io.Writer, data *bundleData) {
	_, _ = fmt.Fprint(w, "## LimitRanges\n\n")
	if len(data.LimitRanges) == 0 {
		_, _ = fmt.Fprint(w, "_No LimitRanges found in namespace._\n\n---\n\n")
		return
	}

	_, _ = fmt.Fprint(w, "| Name | Type | Resource | Min | Max |\n")
	_, _ = fmt.Fprint(w, "|------|------|----------|-----|-----|\n")
	for _, lr := range data.LimitRanges {
		minVal := "-"
		if lr.Min != "" {
			minVal = mdEscape(lr.Min)
		}
		maxVal := "-"
		if lr.Max != "" {
			maxVal = mdEscape(lr.Max)
		}
		_, _ = fmt.Fprintf(w, "| %s | %s | %s | %s | %s |\n",
			mdEscape(lr.Name), mdEscape(lr.Type),
			mdEscape(lr.Resource), minVal, maxVal)
	}
	_, _ = fmt.Fprint(w, "\n---\n\n")
}

func writeBundlePDBsSection(w io.Writer, data *bundleData) {
	_, _ = fmt.Fprint(w, "## PodDisruptionBudgets\n\n")
	if len(data.PDBs) == 0 {
		_, _ = fmt.Fprint(w, "_No PodDisruptionBudgets found in namespace._\n\n---\n\n")
		return
	}

	_, _ = fmt.Fprint(w, "| Name | Min Available | Max Unavailable |\n")
	_, _ = fmt.Fprint(w, "|------|--------------|----------------|\n")
	for _, pdb := range data.PDBs {
		minAvail := "-"
		if pdb.MinAvailable != "" {
			minAvail = mdEscape(pdb.MinAvailable)
		}
		maxUnavail := "-"
		if pdb.MaxUnavailable != "" {
			maxUnavail = mdEscape(pdb.MaxUnavailable)
		}
		_, _ = fmt.Fprintf(w, "| %s | %s | %s |\n",
			mdEscape(pdb.Name), minAvail, maxUnavail)
	}
	_, _ = fmt.Fprint(w, "\n---\n\n")
}

func writeBundleNodeCapacitySection(w io.Writer, data *bundleData) {
	_, _ = fmt.Fprint(w, "## Node Capacity\n\n")
	if data.NodeCapacity == nil {
		_, _ = fmt.Fprint(w, "_Node capacity information unavailable._\n\n---\n\n")
		return
	}

	nc := data.NodeCapacity
	_, _ = fmt.Fprint(w, "| Metric | Value |\n")
	_, _ = fmt.Fprint(w, "|--------|-------|\n")
	_, _ = fmt.Fprintf(w, "| Total Nodes | %d |\n", nc.TotalNodes)
	_, _ = fmt.Fprintf(w, "| Allocatable CPU | %s |\n", nc.AllocCPU.String())
	_, _ = fmt.Fprintf(w, "| Allocatable Memory | %s |\n", nc.AllocMemory.String())
	_, _ = fmt.Fprintf(w, "| Tainted Nodes | %d |\n", nc.TaintedNodes)
	_, _ = fmt.Fprint(w, "\n---\n\n")
}

func writeBundleRecommendations(w io.Writer, data *bundleData) {
	_, _ = fmt.Fprint(w, "## Recommendations\n\n")
	a := data.StatusReport.Analysis

	if len(a.Actions) > 0 {
		_, _ = fmt.Fprint(w, "### Actions\n\n")
		for _, action := range a.Actions {
			_, _ = fmt.Fprintf(w, "- %s\n", mdEscape(action))
		}
		_, _ = fmt.Fprintln(w)
	}

	if len(a.Suggestions) > 0 {
		_, _ = fmt.Fprint(w, "### Suggestions\n\n")
		for _, s := range a.Suggestions {
			_, _ = fmt.Fprintf(w, "- %s\n", mdEscape(s.Description))
		}
		_, _ = fmt.Fprintln(w)
	}

	if len(a.Interpretation) > 0 {
		_, _ = fmt.Fprint(w, "### Interpretation\n\n")
		for _, interp := range a.Interpretation {
			_, _ = fmt.Fprintf(w, "- %s\n", mdEscape(interp))
		}
		_, _ = fmt.Fprintln(w)
	}

	if len(a.Actions) == 0 && len(a.Suggestions) == 0 && len(a.Interpretation) == 0 {
		_, _ = fmt.Fprint(w, "_No recommendations available._\n")
	}

	_, _ = fmt.Fprint(w, "\n---\n\n")
}

func writeBundleFullAnalysis(w io.Writer, data *bundleData) {
	_, _ = fmt.Fprint(w, "## Full Analysis Report\n\n")
	_, _ = fmt.Fprint(w, "<details><summary>Raw JSON Analysis</summary>\n\n")
	_, _ = fmt.Fprint(w, "```json\n")

	analysisJSON, err := json.MarshalIndent(data.StatusReport.Analysis, "", "  ")
	if err != nil {
		_, _ = fmt.Fprintf(w, "Error serializing analysis: %v\n", err)
	} else {
		_, _ = w.Write(analysisJSON)
	}

	_, _ = fmt.Fprint(w, "\n```\n\n</details>\n\n")
}
