package retrospective

import (
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/mattsu2020/kubectl-hpa-status/pkg/hpa/internal/clock"
	"github.com/mattsu2020/kubectl-hpa-status/pkg/hpa/rendutil"
	"github.com/mattsu2020/kubectl-hpa-status/pkg/style"
)

// WriteTimeline renders a Timeline as a compact
// text timeline matching the user-facing output format:
//
//	10:01 desired 3 -> 5   cpu 142% over target
//	10:02 scaleUp limited by policy: +2 pods / 60s
func WriteTimeline(w io.Writer, tl Timeline, theme style.Theme) error {
	var out strings.Builder

	header := fmt.Sprintf("HPA Scaling Timeline: %s (%s)  since %s ago",
		tl.HPAName, tl.Namespace, formatDuration(clock.Now().Sub(tl.Since)))
	out.WriteString(theme.Header.Render(header) + "\n\n")

	if len(tl.Warnings) > 0 {
		for _, warn := range tl.Warnings {
			out.WriteString(theme.Warning.Render(fmt.Sprintf("Warning: %s", warn)) + "\n")
		}
		out.WriteString("\n")
	}

	if len(tl.Entries) == 0 {
		out.WriteString("No scaling events found in the requested time window.\n\n")
	} else {
		for _, entry := range tl.Entries {
			timeStr := entry.Timestamp.Format("15:04:05")
			prefix := categoryPrefix(entry.Category)
			out.WriteString(fmt.Sprintf("%s %s%s\n", timeStr, prefix, entry.Message))
		}
		out.WriteString("\n")
	}

	out.WriteString("Note: " + tl.Disclaimer + "\n")

	_, err := io.WriteString(w, out.String())
	return err
}

// WriteMarkdown renders a Timeline as a Markdown document.
func WriteMarkdown(w io.Writer, tl Timeline) error {
	var out strings.Builder

	out.WriteString(fmt.Sprintf("# HPA Scaling Timeline: %s/%s\n\n", tl.Namespace, tl.HPAName))
	out.WriteString(fmt.Sprintf("- **Since:** %s\n- **Until:** %s\n- **Entries:** %d\n\n",
		tl.Since.Format(time.RFC3339), tl.Until.Format(time.RFC3339), len(tl.Entries)))

	if len(tl.Warnings) > 0 {
		out.WriteString("## Warnings\n\n")
		for _, warn := range tl.Warnings {
			out.WriteString(fmt.Sprintf("- %s\n", rendutil.EscapeMarkdown(warn)))
		}
		out.WriteString("\n")
	}

	if len(tl.Entries) > 0 {
		out.WriteString("| Time | Category | Message | Source | Confidence |\n")
		out.WriteString("|------|----------|---------|--------|------------|\n")
		for _, entry := range tl.Entries {
			out.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s |\n",
				entry.Timestamp.Format("15:04:05"),
				entry.Category,
				rendutil.EscapeMarkdown(entry.Message),
				entry.Source,
				entry.Confidence))
		}
		out.WriteString("\n")
	}

	out.WriteString(fmt.Sprintf("> %s\n", rendutil.EscapeMarkdown(tl.Disclaimer)))

	_, err := io.WriteString(w, out.String())
	return err
}

// WriteHTML renders a Timeline as a standalone HTML page.
func WriteHTML(w io.Writer, tl Timeline) error {
	var out strings.Builder

	out.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>HPA Scaling Timeline: `)
	out.WriteString(rendutil.HTMLEscape(tl.HPAName))
	out.WriteString("</title>\n<style>\n")
	out.WriteString(rendutil.HTMLCSS())
	out.WriteString("</style>\n</head>\n<body>\n")

	out.WriteString(fmt.Sprintf("<h1>HPA Scaling Timeline: %s/%s</h1>\n", rendutil.HTMLEscape(tl.Namespace), rendutil.HTMLEscape(tl.HPAName)))
	out.WriteString(fmt.Sprintf("<p>Since: %s | Until: %s | Entries: %d</p>\n",
		tl.Since.Format(time.RFC3339), tl.Until.Format(time.RFC3339), len(tl.Entries)))

	if len(tl.Warnings) > 0 {
		out.WriteString("<h2>Warnings</h2>\n<ul>\n")
		for _, warn := range tl.Warnings {
			out.WriteString(fmt.Sprintf("<li>%s</li>\n", rendutil.HTMLEscape(warn)))
		}
		out.WriteString("</ul>\n")
	}

	if len(tl.Entries) > 0 {
		out.WriteString("<table>\n<tr><th>Time</th><th>Category</th><th>Message</th><th>Source</th><th>Confidence</th></tr>\n")
		for _, entry := range tl.Entries {
			out.WriteString("<tr>")
			out.WriteString(fmt.Sprintf("<td>%s</td>", entry.Timestamp.Format("15:04:05")))
			out.WriteString(fmt.Sprintf("<td>%s</td>", rendutil.HTMLEscape(entry.Category)))
			out.WriteString(fmt.Sprintf("<td>%s</td>", rendutil.HTMLEscape(entry.Message)))
			out.WriteString(fmt.Sprintf("<td>%s</td>", rendutil.HTMLEscape(entry.Source)))
			out.WriteString(fmt.Sprintf("<td>%s</td>", rendutil.HTMLEscape(entry.Confidence)))
			out.WriteString("</tr>\n")
		}
		out.WriteString("</table>\n")
	}

	out.WriteString(fmt.Sprintf("<p class=\"disclaimer\">%s</p>\n", rendutil.HTMLEscape(tl.Disclaimer)))
	out.WriteString("<footer>Generated by kubectl-hpa-status</footer>\n")
	out.WriteString("</body>\n</html>\n")

	_, err := io.WriteString(w, out.String())
	return err
}

func categoryPrefix(category string) string {
	switch category {
	case "rescale", "metric-change", "metrics-unavailable", "scaling-limited", "stabilized", "policy-limited":
		return ""
	default:
		if category == "" {
			return ""
		}
		return category + " "
	}
}

// formatDuration returns a human-readable duration string like "30m" or "1h30m".
func formatDuration(d time.Duration) string {
	d = d.Round(time.Minute)
	if d < time.Minute {
		return "0m"
	}
	h := int(d.Hours())
	m := int(d.Minutes()) % 60
	if h > 0 && m > 0 {
		return fmt.Sprintf("%dh%dm", h, m)
	}
	if h > 0 {
		return fmt.Sprintf("%dh", h)
	}
	return fmt.Sprintf("%dm", m)
}

// WriteReplayText renders a ReplayAnalysis as a text timeline with
// bottleneck markers, control cycles, and stabilization windows.
func WriteReplayText(w io.Writer, analysis *ReplayAnalysis, tl Timeline, theme style.Theme) error {
	var out strings.Builder

	out.WriteString(theme.Header.Render(fmt.Sprintf("HPA Replay Analysis: %s (%s)", tl.HPAName, tl.Namespace)) + "\n")
	out.WriteString(fmt.Sprintf("Period: %s - %s\n\n",
		tl.Since.Format("15:04"), tl.Until.Format("15:04")))

	out.WriteString(replayBottlenecksText(analysis))
	out.WriteString(replayControlCyclesText(analysis))
	out.WriteString(replayStabilizationWindowsText(analysis))
	out.WriteString(replayToleranceEffectsText(analysis))

	// Summary.
	out.WriteString(theme.SummaryColor(analysis.Summary))
	out.WriteString("\n\n")
	out.WriteString(theme.Dim.Render("Note: "+tl.Disclaimer) + "\n")

	_, err := io.WriteString(w, out.String())
	return err
}

// replayBottlenecksText renders the Bottlenecks section of the replay text output.
func replayBottlenecksText(analysis *ReplayAnalysis) string {
	if len(analysis.Bottlenecks) == 0 {
		return ""
	}
	var out strings.Builder
	out.WriteString(fmt.Sprintf("Bottlenecks (%d):\n", len(analysis.Bottlenecks)))
	for _, b := range analysis.Bottlenecks {
		out.WriteString(replayBottleneckLine(b))
	}
	out.WriteString("\n")
	return out.String()
}

// replayBottleneckLine renders a single bottleneck line.
func replayBottleneckLine(b BottleneckMarker) string {
	severityPrefix := "[LOW] "
	switch b.Severity {
	case "high":
		severityPrefix = "[HIGH] "
	case "medium":
		severityPrefix = "[MED] "
	}
	timeStr := b.Timestamp.Format("15:04")
	durationStr := ""
	if b.Duration > 0 {
		durationStr = fmt.Sprintf(" (duration: %s)", formatDuration(b.Duration))
	}
	return fmt.Sprintf("  %s%s %s — %s%s\n", severityPrefix, timeStr, b.Type, b.Message, durationStr)
}

// replayControlCyclesText renders the Control Cycles section of the replay text output.
func replayControlCyclesText(analysis *ReplayAnalysis) string {
	if len(analysis.ControlCycles) == 0 {
		return ""
	}
	var out strings.Builder
	out.WriteString(fmt.Sprintf("Control Cycles (%d):\n", len(analysis.ControlCycles)))
	for _, c := range analysis.ControlCycles {
		out.WriteString(replayControlCycleLine(c, analysis.StabilizationWindows))
	}
	out.WriteString("\n")
	return out.String()
}

// replayControlCycleLine renders a single control cycle line including any
// stabilization note.
func replayControlCycleLine(c ControlCycle, windows []StabilizationWindow) string {
	startStr := c.Start.Format("15:04")
	endStr := c.End.Format("15:04")
	decisionText := replayDecisionText(c)
	stabNote := replayStabilizationNote(c.End, windows)
	return fmt.Sprintf("  %s-%s %s (%d → %d)%s\n",
		startStr, endStr, decisionText, c.InputReplicas, c.OutputReplicas, stabNote)
}

// replayDecisionText renders the decision portion of a control cycle line.
func replayDecisionText(c ControlCycle) string {
	switch {
	case c.Decision == "no-change" && c.MetricDriver != "unknown":
		return fmt.Sprintf("no-change (%s within tolerance)", c.MetricDriver)
	case c.Decision == "capped":
		return "scale-up capped by maxReplicas"
	case c.MetricDriver != "unknown":
		return fmt.Sprintf("%s (%s above target)", c.Decision, c.MetricDriver)
	}
	return c.Decision
}

// replayStabilizationNote returns the stabilization suffix for a control cycle
// end time, or an empty string when no window applies.
func replayStabilizationNote(end time.Time, windows []StabilizationWindow) string {
	for _, sw := range windows {
		if end.After(sw.Start) && end.Before(sw.End) {
			return fmt.Sprintf(" (stabilization active, suppressed: -%d)", sw.SuppressedScaleDown)
		}
	}
	return ""
}

// replayStabilizationWindowsText renders the Stabilization Windows section.
func replayStabilizationWindowsText(analysis *ReplayAnalysis) string {
	if len(analysis.StabilizationWindows) == 0 {
		return ""
	}
	var out strings.Builder
	out.WriteString(fmt.Sprintf("Stabilization Windows (%d):\n", len(analysis.StabilizationWindows)))
	for _, sw := range analysis.StabilizationWindows {
		startStr := sw.Start.Format("15:04")
		endStr := sw.End.Format("15:04")
		durationStr := formatDuration(sw.Duration)
		out.WriteString(fmt.Sprintf("  %s - %s (%s) — suppressed scale-down of %d replicas\n",
			startStr, endStr, durationStr, sw.SuppressedScaleDown))
	}
	out.WriteString("\n")
	return out.String()
}

// replayToleranceEffectsText renders the Tolerance Effects section.
func replayToleranceEffectsText(analysis *ReplayAnalysis) string {
	if len(analysis.ReplayToleranceEffects) == 0 {
		return ""
	}
	var out strings.Builder
	out.WriteString(fmt.Sprintf("Tolerance Effects (%d):\n", len(analysis.ReplayToleranceEffects)))
	for _, te := range analysis.ReplayToleranceEffects {
		timeStr := te.Timestamp.Format("15:04")
		suppressedText := "suppressed"
		if !te.Suppressed {
			suppressedText = "not suppressed"
		}
		out.WriteString(fmt.Sprintf("  %s %s ratio %.2f tolerance %.2f — %s\n",
			timeStr, te.MetricName, te.ActualRatio, te.Tolerance, suppressedText))
	}
	out.WriteString("\n")
	return out.String()
}

// WriteReplayMarkdown renders a ReplayAnalysis as a Markdown document.
func WriteReplayMarkdown(w io.Writer, analysis *ReplayAnalysis, tl Timeline) error {
	var out strings.Builder

	out.WriteString(fmt.Sprintf("# HPA Replay Analysis: %s/%s\n\n", tl.Namespace, tl.HPAName))
	out.WriteString(fmt.Sprintf("- **Period:** %s - %s\n", tl.Since.Format(time.RFC3339), tl.Until.Format(time.RFC3339)))
	out.WriteString(fmt.Sprintf("- **Bottlenecks:** %d\n", len(analysis.Bottlenecks)))
	out.WriteString(fmt.Sprintf("- **Control Cycles:** %d\n", len(analysis.ControlCycles)))
	out.WriteString(fmt.Sprintf("- **Stabilization Windows:** %d\n", len(analysis.StabilizationWindows)))
	out.WriteString(fmt.Sprintf("- **Tolerance Effects:** %d\n\n", len(analysis.ReplayToleranceEffects)))

	// Bottlenecks section.
	if len(analysis.Bottlenecks) > 0 {
		out.WriteString("## Bottlenecks\n\n")
		out.WriteString("| Time | Type | Severity | Message | Duration |\n")
		out.WriteString("|------|------|----------|---------|----------|\n")
		for _, b := range analysis.Bottlenecks {
			durationStr := "0s"
			if b.Duration > 0 {
				durationStr = formatDuration(b.Duration)
			}
			out.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s |\n",
				b.Timestamp.Format("15:04"),
				b.Type,
				b.Severity,
				rendutil.EscapeMarkdown(b.Message),
				durationStr))
		}
		out.WriteString("\n")
	}

	// Control Cycles section.
	if len(analysis.ControlCycles) > 0 {
		out.WriteString("## Control Cycles\n\n")
		out.WriteString("| Start | End | Decision | Input Replicas | Output Replicas | Metric Driver |\n")
		out.WriteString("|-------|-----|----------|----------------|-----------------|----------------|\n")
		for _, c := range analysis.ControlCycles {
			out.WriteString(fmt.Sprintf("| %s | %s | %s | %d | %d | %s |\n",
				c.Start.Format("15:04"),
				c.End.Format("15:04"),
				c.Decision,
				c.InputReplicas,
				c.OutputReplicas,
				c.MetricDriver))
		}
		out.WriteString("\n")
	}

	// Stabilization Windows section.
	if len(analysis.StabilizationWindows) > 0 {
		out.WriteString("## Stabilization Windows\n\n")
		out.WriteString("| Start | End | Duration | Suppressed Scale-Down |\n")
		out.WriteString("|-------|-----|----------|----------------------|\n")
		for _, sw := range analysis.StabilizationWindows {
			out.WriteString(fmt.Sprintf("| %s | %s | %s | %d |\n",
				sw.Start.Format("15:04"),
				sw.End.Format("15:04"),
				formatDuration(sw.Duration),
				sw.SuppressedScaleDown))
		}
		out.WriteString("\n")
	}

	// Tolerance Effects section.
	if len(analysis.ReplayToleranceEffects) > 0 {
		out.WriteString("## Tolerance Effects\n\n")
		out.WriteString("| Time | Metric | Actual Ratio | Tolerance | Suppressed |\n")
		out.WriteString("|------|--------|--------------|------------|------------|\n")
		for _, te := range analysis.ReplayToleranceEffects {
			suppressed := "No"
			if te.Suppressed {
				suppressed = "Yes"
			}
			out.WriteString(fmt.Sprintf("| %s | %s | %.2f | %.2f | %s |\n",
				te.Timestamp.Format("15:04"),
				te.MetricName,
				te.ActualRatio,
				te.Tolerance,
				suppressed))
		}
		out.WriteString("\n")
	}

	// Summary.
	out.WriteString(fmt.Sprintf("## Summary\n\n%s\n\n", rendutil.EscapeMarkdown(analysis.Summary)))
	out.WriteString(fmt.Sprintf("> %s\n", rendutil.EscapeMarkdown(tl.Disclaimer)))

	_, err := io.WriteString(w, out.String())
	return err
}

// WriteReplayHTML renders a ReplayAnalysis as a standalone HTML page.
func WriteReplayHTML(w io.Writer, analysis *ReplayAnalysis, tl Timeline) error {
	var out strings.Builder

	out.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>HPA Replay Analysis: `)
	out.WriteString(rendutil.HTMLEscape(tl.HPAName))
	out.WriteString("</title>\n<style>\n")
	out.WriteString(rendutil.HTMLCSS())
	out.WriteString(`
.severity-high { color: #d32f2f; font-weight: bold; }
.severity-medium { color: #f57c00; font-weight: bold; }
.severity-low { color: #388e3c; }
.bottleneck-row { margin-bottom: 8px; }
.control-cycle-row { margin-bottom: 8px; }
`)
	out.WriteString("</style>\n</head>\n<body>\n")

	out.WriteString(fmt.Sprintf("<h1>HPA Replay Analysis: %s/%s</h1>\n", rendutil.HTMLEscape(tl.Namespace), rendutil.HTMLEscape(tl.HPAName)))
	out.WriteString(fmt.Sprintf("<p>Period: %s - %s</p>\n",
		tl.Since.Format(time.RFC3339), tl.Until.Format(time.RFC3339)))

	// Summary stats.
	out.WriteString("<div class=\"summary\">\n")
	out.WriteString(fmt.Sprintf("<p><strong>Bottlenecks:</strong> %d\n", len(analysis.Bottlenecks)))
	out.WriteString(fmt.Sprintf("<strong>Control Cycles:</strong> %d\n", len(analysis.ControlCycles)))
	out.WriteString(fmt.Sprintf("<strong>Stabilization Windows:</strong> %d\n", len(analysis.StabilizationWindows)))
	out.WriteString(fmt.Sprintf("<strong>Tolerance Effects:</strong> %d</p>\n", len(analysis.ReplayToleranceEffects)))
	out.WriteString("</div>\n")

	// Bottlenecks section.
	if len(analysis.Bottlenecks) > 0 {
		out.WriteString("<h2>Bottlenecks</h2>\n<table>\n<tr><th>Time</th><th>Type</th><th>Severity</th><th>Message</th><th>Duration</th></tr>\n")
		for _, b := range analysis.Bottlenecks {
			severityClass := "severity-" + strings.ToLower(b.Severity)
			durationStr := "0s"
			if b.Duration > 0 {
				durationStr = formatDuration(b.Duration)
			}
			out.WriteString("<tr>")
			out.WriteString(fmt.Sprintf("<td>%s</td>", b.Timestamp.Format("15:04")))
			out.WriteString(fmt.Sprintf("<td>%s</td>", rendutil.HTMLEscape(b.Type)))
			out.WriteString(fmt.Sprintf("<td class=\"%s\">%s</td>", severityClass, rendutil.HTMLEscape(b.Severity)))
			out.WriteString(fmt.Sprintf("<td>%s</td>", rendutil.HTMLEscape(b.Message)))
			out.WriteString(fmt.Sprintf("<td>%s</td>", durationStr))
			out.WriteString("</tr>\n")
		}
		out.WriteString("</table>\n")
	}

	// Control Cycles section.
	if len(analysis.ControlCycles) > 0 {
		out.WriteString("<h2>Control Cycles</h2>\n<table>\n<tr><th>Start</th><th>End</th><th>Decision</th><th>Input</th><th>Output</th><th>Metric Driver</th></tr>\n")
		for _, c := range analysis.ControlCycles {
			out.WriteString("<tr>")
			out.WriteString(fmt.Sprintf("<td>%s</td>", c.Start.Format("15:04")))
			out.WriteString(fmt.Sprintf("<td>%s</td>", c.End.Format("15:04")))
			out.WriteString(fmt.Sprintf("<td>%s</td>", rendutil.HTMLEscape(c.Decision)))
			out.WriteString(fmt.Sprintf("<td>%d</td>", c.InputReplicas))
			out.WriteString(fmt.Sprintf("<td>%d</td>", c.OutputReplicas))
			out.WriteString(fmt.Sprintf("<td>%s</td>", rendutil.HTMLEscape(c.MetricDriver)))
			out.WriteString("</tr>\n")
		}
		out.WriteString("</table>\n")
	}

	// Stabilization Windows section.
	if len(analysis.StabilizationWindows) > 0 {
		out.WriteString("<h2>Stabilization Windows</h2>\n<table>\n<tr><th>Start</th><th>End</th><th>Duration</th><th>Suppressed Scale-Down</th></tr>\n")
		for _, sw := range analysis.StabilizationWindows {
			out.WriteString("<tr>")
			out.WriteString(fmt.Sprintf("<td>%s</td>", sw.Start.Format("15:04")))
			out.WriteString(fmt.Sprintf("<td>%s</td>", sw.End.Format("15:04")))
			out.WriteString(fmt.Sprintf("<td>%s</td>", formatDuration(sw.Duration)))
			out.WriteString(fmt.Sprintf("<td>%d</td>", sw.SuppressedScaleDown))
			out.WriteString("</tr>\n")
		}
		out.WriteString("</table>\n")
	}

	// Tolerance Effects section.
	if len(analysis.ReplayToleranceEffects) > 0 {
		out.WriteString("<h2>Tolerance Effects</h2>\n<table>\n<tr><th>Time</th><th>Metric</th><th>Actual Ratio</th><th>Tolerance</th><th>Suppressed</th></tr>\n")
		for _, te := range analysis.ReplayToleranceEffects {
			suppressed := "No"
			if te.Suppressed {
				suppressed = "Yes"
			}
			out.WriteString("<tr>")
			out.WriteString(fmt.Sprintf("<td>%s</td>", te.Timestamp.Format("15:04")))
			out.WriteString(fmt.Sprintf("<td>%s</td>", rendutil.HTMLEscape(te.MetricName)))
			out.WriteString(fmt.Sprintf("<td>%.2f</td>", te.ActualRatio))
			out.WriteString(fmt.Sprintf("<td>%.2f</td>", te.Tolerance))
			out.WriteString(fmt.Sprintf("<td>%s</td>", suppressed))
			out.WriteString("</tr>\n")
		}
		out.WriteString("</table>\n")
	}

	// Summary.
	out.WriteString(fmt.Sprintf("<h2>Summary</h2>\n<p>%s</p>\n", rendutil.HTMLEscape(analysis.Summary)))
	out.WriteString(fmt.Sprintf("<p class=\"disclaimer\">%s</p>\n", rendutil.HTMLEscape(tl.Disclaimer)))
	out.WriteString("<footer>Generated by kubectl-hpa-status</footer>\n")
	out.WriteString("</body>\n</html>\n")

	_, err := io.WriteString(w, out.String())
	return err
}
