package rendutil

import (
	"strings"
	"testing"
)

func sampleItems() []ListItemView {
	return []ListItemView{
		{Namespace: "ns-a", Name: "web", Target: "Deployment/web", Current: 3, Desired: 5, Min: 1, Max: 10, Health: "OK", HealthScore: 92, Summary: "healthy"},
		// Fields containing Markdown/HTML-special characters must be escaped.
		{Namespace: "ns|b", Name: "api<x>", Target: "Deployment/api", Current: 0, Desired: 1, Min: 1, Max: 5, Health: "LIMITED", HealthScore: 40, Summary: "a & b"},
	}
}

func TestWriteMarkdownList(t *testing.T) {
	var out strings.Builder
	if err := WriteMarkdownList(&out, sampleItems()); err != nil {
		t.Fatalf("WriteMarkdownList returned error: %v", err)
	}
	got := out.String()
	for _, want := range []string{
		"# HPA List Report",
		"| Namespace | Name | Target |",
		"| ns-a | web | Deployment/web |",
		"| 3 | 5 | 1 | 10 |",
		"ns\\|b",       // pipe inside namespace is escaped
		"api&lt;x&gt;", // angle brackets escaped
		"a &amp; b",
		"Generated by kubectl-hpa-status",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("WriteMarkdownList output missing %q:\n%s", want, got)
		}
	}
	if !strings.Contains(got, "| 92 |") {
		t.Fatalf("WriteMarkdownList missing health score column:\n%s", got)
	}
}

func TestWriteMarkdownList_Empty(t *testing.T) {
	var out strings.Builder
	if err := WriteMarkdownList(&out, nil); err != nil {
		t.Fatalf("WriteMarkdownList returned error: %v", err)
	}
	got := out.String()
	if !strings.Contains(got, "_No HPAs found._") {
		t.Fatalf("WriteMarkdownList empty output missing placeholder:\n%s", got)
	}
	if !strings.Contains(got, "# HPA List Report") {
		t.Fatalf("WriteMarkdownList empty output missing header:\n%s", got)
	}
}

func TestWriteHTMLList(t *testing.T) {
	var out strings.Builder
	if err := WriteHTMLList(&out, sampleItems()); err != nil {
		t.Fatalf("WriteHTMLList returned error: %v", err)
	}
	got := out.String()
	for _, want := range []string{
		"<!DOCTYPE html>",
		"<h1>HPA List Report</h1>",
		"<table>",
		"<tr><th>Namespace</th>",
		"ns-a",
		"ns|b", // HTML list does not escape pipes (no markdown context)
		"api&lt;x&gt;",
		"a &amp; b",
		"class=\"health-ok\"",
		"class=\"health-limited\"",
		"<footer>Generated by kubectl-hpa-status</footer>",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("WriteHTMLList output missing %q:\n%s", want, got)
		}
	}
	// Raw angle brackets inside cell text must be gone.
	if strings.Contains(got, "api<x>") {
		t.Fatalf("WriteHTMLList left raw angle brackets in cell text:\n%s", got)
	}
}

func TestWriteHTMLList_Empty(t *testing.T) {
	var out strings.Builder
	if err := WriteHTMLList(&out, nil); err != nil {
		t.Fatalf("WriteHTMLList returned error: %v", err)
	}
	got := out.String()
	if !strings.Contains(got, "No HPAs found.") {
		t.Fatalf("WriteHTMLList empty output missing placeholder:\n%s", got)
	}
	if strings.Contains(got, "<tr>") {
		t.Fatalf("WriteHTMLList empty output should have no table rows:\n%s", got)
	}
}
