package rendutil

import (
	"fmt"
	"io"
	"strings"
)

// ListItemView is the renderer-neutral projection of one HPA list row.
// Keeping it below pkg/hpa and pkg/hpa/render lets both the public compatibility
// facade and the canonical renderer share one implementation without an import
// cycle.
type ListItemView struct {
	Namespace   string
	Name        string
	Target      string
	Current     int32
	Desired     int32
	Min         int32
	Max         int32
	Health      string
	HealthScore int
	Summary     string
}

// WriteMarkdownList writes a list projection as a Markdown table.
func WriteMarkdownList(w io.Writer, items []ListItemView) error {
	var out strings.Builder
	out.WriteString("# HPA List Report\n\n")
	if len(items) == 0 {
		out.WriteString("_No HPAs found._\n")
		_, err := io.WriteString(w, out.String())
		return err
	}

	out.WriteString("| Namespace | Name | Target | Current | Desired | Min | Max | Health | Score | Summary |\n")
	out.WriteString("|-----------|------|--------|---------|---------|-----|-----|--------|-------|--------|\n")
	for _, item := range items {
		fmt.Fprintf(&out, "| %s | %s | %s | %d | %d | %d | %d | %s | %d | %s |\n",
			EscapeMarkdown(item.Namespace),
			EscapeMarkdown(item.Name),
			EscapeMarkdown(item.Target),
			item.Current,
			item.Desired,
			item.Min,
			item.Max,
			EscapeMarkdown(item.Health),
			item.HealthScore,
			EscapeMarkdown(item.Summary),
		)
	}
	out.WriteString("\n---\nGenerated by kubectl-hpa-status\n")
	_, err := io.WriteString(w, out.String())
	return err
}

// WriteHTMLList writes a list projection as a standalone HTML document.
func WriteHTMLList(w io.Writer, items []ListItemView) error {
	var out strings.Builder
	out.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>HPA List Report</title>
<style>
`)
	out.WriteString(HTMLCSS())
	out.WriteString("</style>\n</head>\n<body>\n")
	out.WriteString("<h1>HPA List Report</h1>\n")

	if len(items) == 0 {
		out.WriteString("<p><em>No HPAs found.</em></p>\n")
	} else {
		out.WriteString("<table>\n<tr><th>Namespace</th><th>Name</th><th>Target</th><th>Current</th><th>Desired</th><th>Min</th><th>Max</th><th>Health</th><th>Score</th><th>Summary</th></tr>\n")
		for _, item := range items {
			fmt.Fprintf(&out,
				"<tr><td>%s</td><td>%s</td><td>%s</td><td>%d</td><td>%d</td><td>%d</td><td>%d</td><td>%s</td><td>%d</td><td>%s</td></tr>\n",
				HTMLEscape(item.Namespace),
				HTMLEscape(item.Name),
				HTMLEscape(item.Target),
				item.Current,
				item.Desired,
				item.Min,
				item.Max,
				HTMLHealthBadge(item.Health, item.HealthScore),
				item.HealthScore,
				HTMLEscape(item.Summary),
			)
		}
		out.WriteString("</table>\n")
	}

	out.WriteString("<footer>Generated by kubectl-hpa-status</footer>\n")
	out.WriteString("</body>\n</html>\n")
	_, err := io.WriteString(w, out.String())
	return err
}
